# Generated by Django 4.2.7 on 2023-11-11 23:29

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='body',
            field=martor.models.MartorField(blank=True),
        ),
    ]
