# Generated by Django 4.2.7 on 2023-11-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_section_post_alter_subsection_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('post', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together={('section', 'order')},
        ),
    ]
