# Generated by Django 4.2.7 on 2023-11-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_section_order_subsection_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
