# Generated by Django 4.2.7 on 2023-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomuser",
            name="force_password_reset",
            field=models.BooleanField(default=False),
        ),
    ]
