# Generated by Django 5.0.8 on 2024-11-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_bloomuser_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloomuser",
            name="force_password_reset",
            field=models.BooleanField(
                default=True,
                help_text="Require this user to reset their password the next time they log in",
            ),
        ),
    ]
