# Generated by Django 5.0.8 on 2025-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_bloomuser_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomuser",
            name="login_gov_user_id",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier from Login.gov",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
