# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      python-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      github-actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 14
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      docker-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
