# Generated by Django 4.2.10 on 2024-04-03 05:10

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ODIDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, verbose_name="Section name")),
                ("body", martor.models.MartorField()),
                ("order", models.IntegerField()),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("h2", "Heading 2"),
                            ("h3", "Heading 3"),
                            ("h4", "Heading 4"),
                            ("h5", "Heading 5"),
                            ("h6", "Heading 6"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="odi_documents.odidocument",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("document", "order")},
            },
        ),
    ]
