# Generated by Django 4.2.10 on 2024-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_bloomuser_force_password_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomuser",
            name="group",
            field=models.CharField(
                choices=[
                    ("bloom", "Bloomworks"),
                    ("acf", "ACF: Administration for Children and Families"),
                    ("acl", "ACL: Administration for Community Living"),
                    (
                        "aspr",
                        "ASPR: Administration for Strategic Preparedness and Response",
                    ),
                    ("cdc", "CDC: Centers for Disease Control and Prevention"),
                    ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                    ("hrsa", "HRSA: Health Resources and Services Administration"),
                    ("ihs", "IHS: Indian Health Service"),
                ],
                default="bloom",
                help_text="The OpDiv for this user. If they are a Bloom coaches/admins, this should say 'Bloomworks'.",
                max_length=16,
            ),
        ),
    ]
