# Generated by Django 6.0.4 on 2026-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_bloomuser_login_gov_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloomuser",
            name="group",
            field=models.CharField(
                choices=[
                    ("bloom", "Bloomworks"),
                    ("acf", "ACF: Administration for Children and Families"),
                    ("acl", "ACL: Administration for Community Living"),
                    (
                        "aspr",
                        "ASPR: Administration for Strategic Preparedness and Response",
                    ),
                    ("cdc", "CDC: Centers for Disease Control and Prevention"),
                    ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                    ("hrsa", "HRSA: Health Resources and Services Administration"),
                    ("ihs", "IHS: Indian Health Service"),
                    ("staging", "Staging environment"),
                ],
                default="bloom",
                help_text="The OpDiv for this user. If they are a Bloom coach/admin, this should say 'Bloomworks'.",
                max_length=16,
            ),
        ),
    ]
