# Generated by Django 6.0.5 on 2026-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_bloomuser_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomuser",
            name="is_opdiv_admin",
            field=models.BooleanField(
                default=False,
                help_text="Allow this user to manage other OpDiv users in their group.",
            ),
        ),
    ]
