# Generated by Django 6.0.5 on 2026-05-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_bloomuser_is_opdiv_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomuser",
            name="is_composer_admin",
            field=models.BooleanField(
                default=False,
                help_text="Allow this user to create, edit, publish, unpublish, and archive Composer content guides.",
            ),
        ),
    ]
