# Generated by Django 5.2.7 on 2025-10-17 19:35

import uuid

import django.core.validators
import django.db.models.deletion
import martor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compare", "0003_guides_are_gone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="The filename used to import this document. If re-imported, this value is the most recent filename.",
                        max_length=511,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("bloom", "Bloomworks"),
                            ("acf", "ACF: Administration for Children and Families"),
                            ("acl", "ACL: Administration for Community Living"),
                            (
                                "aspr",
                                "ASPR: Administration for Strategic Preparedness and Response",
                            ),
                            ("cdc", "CDC: Centers for Disease Control and Prevention"),
                            ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                            (
                                "hrsa",
                                "HRSA: Health Resources and Services Administration",
                            ),
                            ("ihs", "IHS: Indian Health Service"),
                            ("staging", "Staging environment"),
                        ],
                        default="bloom",
                        help_text="The OpDiv group for this document. The group controls access to a document. The 'Bloomworks' group hides documents from OpDiv users.",
                        max_length=16,
                        validators=[django.core.validators.MaxLengthValidator(16)],
                    ),
                ),
                (
                    "opdiv",
                    models.CharField(
                        help_text="The HHS operating division (eg, HRSA, CDC)",
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                        verbose_name="Operating Division",
                    ),
                ),
                (
                    "archived",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="Archived documents are soft-deleted: they are not visible in the UI but can be recovered by superusers.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        help_text="The official name for this NOFO. It will be public when the NOFO is published.",
                        max_length=250,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name="Content Guide title",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        help_text="Visibility/lifecycle for writers. NOFO Writers only see ACTIVE.",
                        max_length=32,
                        validators=[django.core.validators.MaxLengthValidator(32)],
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestors",
                        to="composer.contentguide",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The last logged-in user who modified this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ContentGuideSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=250,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name="Section name",
                    ),
                ),
                (
                    "html_id",
                    models.CharField(
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                    ),
                ),
                ("order", models.IntegerField(null=True)),
                (
                    "has_section_page",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this section will have its own page and icon in the ToC.",
                        verbose_name="Has section page?",
                    ),
                ),
                (
                    "html_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1023,
                        validators=[django.core.validators.MaxLengthValidator(1023)],
                        verbose_name="HTML class attribute",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="composer.contentguide",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("document", "order")},
            },
        ),
        migrations.CreateModel(
            name="ContentGuideSubsection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        validators=[django.core.validators.MaxLengthValidator(400)],
                        verbose_name="Subsection name",
                    ),
                ),
                (
                    "html_id",
                    models.CharField(
                        blank=True,
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                        verbose_name="HTML id attribute",
                    ),
                ),
                (
                    "html_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1023,
                        validators=[django.core.validators.MaxLengthValidator(1023)],
                        verbose_name="HTML class attribute",
                    ),
                ),
                ("order", models.IntegerField(null=True)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("h2", "Heading 2"),
                            ("h3", "Heading 3"),
                            ("h4", "Heading 4"),
                            ("h5", "Heading 5"),
                            ("h6", "Heading 6"),
                            ("h7", "Heading 7"),
                        ],
                        max_length=2,
                        validators=[django.core.validators.MaxLengthValidator(2)],
                    ),
                ),
                (
                    "callout_box",
                    models.BooleanField(
                        default=False,
                        help_text="Make this subsection a callout box.",
                        verbose_name="Callout box",
                    ),
                ),
                (
                    "body",
                    martor.models.MartorField(
                        blank=True, verbose_name="Content of subsection"
                    ),
                ),
                (
                    "edit_mode",
                    models.CharField(
                        choices=[
                            ("full", "Edit all text"),
                            ("variables", "Edit variables"),
                            ("yes_no", "Select Yes/No only"),
                            ("locked", "Content is locked"),
                        ],
                        default="full",
                        help_text="Decide how NOFO Writers can edit this subsection.",
                        max_length=16,
                    ),
                ),
                (
                    "instructions",
                    martor.models.MartorField(
                        blank=True,
                        help_text="Guidance for NOFO Writers on filling out this section.",
                        verbose_name="Content of subsection",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to show this section in the content guide.",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="composer.contentguidesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("section", "order")},
            },
        ),
    ]
