# Generated by Django 5.2.7 on 2025-10-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="edit_mode",
            field=models.CharField(
                choices=[
                    ("full", "Edit all text"),
                    ("variables", "Edit variables"),
                    ("yes_no", "Select Yes/No only"),
                    ("locked", "Content is locked"),
                ],
                default="locked",
                help_text="Decide how NOFO Writers can edit this subsection.",
                max_length=16,
            ),
        ),
    ]
