# Generated by Django 5.2.8 on 2025-11-19 22:08

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0002_alter_contentguidesubsection_edit_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGuideInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="The filename used to import this document. If re-imported, this value is the most recent filename.",
                        max_length=511,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("bloom", "Bloomworks"),
                            ("acf", "ACF: Administration for Children and Families"),
                            ("acl", "ACL: Administration for Community Living"),
                            (
                                "aspr",
                                "ASPR: Administration for Strategic Preparedness and Response",
                            ),
                            ("cdc", "CDC: Centers for Disease Control and Prevention"),
                            ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                            (
                                "hrsa",
                                "HRSA: Health Resources and Services Administration",
                            ),
                            ("ihs", "IHS: Indian Health Service"),
                            ("staging", "Staging environment"),
                        ],
                        default="bloom",
                        help_text="The OpDiv group for this document. The group controls access to a document. The 'Bloomworks' group hides documents from OpDiv users.",
                        max_length=16,
                        validators=[django.core.validators.MaxLengthValidator(16)],
                    ),
                ),
                (
                    "opdiv",
                    models.CharField(
                        help_text="The HHS operating division (eg, HRSA, CDC)",
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                        verbose_name="Operating Division",
                    ),
                ),
                (
                    "archived",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="Archived documents are soft-deleted: they are not visible in the UI but can be recovered by superusers.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        help_text="The official name for this NOFO. It will be public when the NOFO is published.",
                        max_length=250,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name="Content Guide title",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft")],
                        default="draft",
                        max_length=32,
                        validators=[django.core.validators.MaxLengthValidator(32)],
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="A name that makes it easier to find this NOFO in a list. It won’t be public.",
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="The official opportunity number for this NOFO.",
                        max_length=200,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                        verbose_name="Opportunity number",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True,
                        help_text="The agency within the operating division (eg, Bureau of Health Workforce)",
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                        verbose_name="Agency",
                    ),
                ),
                (
                    "conditional_questions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Yes/No answers keyed by question key (e.g. intergov_review: true).",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The original Content Guide this instance was created from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="composer.contentguide",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestors",
                        to="composer.contentguideinstance",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The last logged-in user who modified this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
