# Generated by Django 5.2.8 on 2025-11-19 22:12

import django.db.models.deletion
from django.db import migrations, models


def copy_document_to_content_guide(apps, schema_editor):
    ContentGuideSection = apps.get_model("composer", "ContentGuideSection")
    for section in ContentGuideSection.objects.all():
        # copy the old document FK into the new content_guide FK
        section.content_guide_id = section.document_id
        section.save(update_fields=["content_guide"])


def copy_content_guide_to_document(apps, schema_editor):
    # Reverse migration: restore document from content_guide
    ContentGuideSection = apps.get_model("composer", "ContentGuideSection")
    for section in ContentGuideSection.objects.all():
        section.document_id = section.content_guide_id
        section.save(update_fields=["document"])


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0003_contentguideinstance"),
    ]

    operations = [
        # 0. Relax the old document FK to be nullable. Else reverse migrations don't work
        migrations.AlterField(
            model_name="contentguidesection",
            name="document",
            field=models.ForeignKey(
                to="composer.contentguide",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                null=True,
                blank=True,
            ),
        ),
        # 1. Add new FKs
        migrations.AddField(
            model_name="contentguidesection",
            name="content_guide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="composer.contentguide",
            ),
        ),
        migrations.AddField(
            model_name="contentguidesection",
            name="content_guide_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="composer.contentguideinstance",
            ),
        ),
        # 2. Data migration: document → content_guide
        migrations.RunPython(
            copy_document_to_content_guide,
            reverse_code=copy_content_guide_to_document,
        ),
        # 3. Switch unique_together to the new triple
        migrations.AlterUniqueTogether(
            name="contentguidesection",
            unique_together={("content_guide", "content_guide_instance", "order")},
        ),
        # 4. Now we can safely remove the old field
        migrations.RemoveField(
            model_name="contentguidesection",
            name="document",
        ),
        # 5. Add the "exactly one parent" constraint
        migrations.AddConstraint(
            model_name="contentguidesection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("content_guide__isnull", False),
                        ("content_guide_instance__isnull", True),
                    ),
                    models.Q(
                        ("content_guide__isnull", True),
                        ("content_guide_instance__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="section_has_exactly_one_parent",
            ),
        ),
    ]
