# Generated by Django 5.2.7 on 2025-11-24 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0005_alter_contentguidesection_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguide",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                help_text="Visibility/lifecycle for writers. NOFO Writers only see Published.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
    ]
