# Generated by Django 5.2.9 on 2025-12-05 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0006_alter_contentguide_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentguideinstance",
            name="activity_code",
            field=models.CharField(
                blank=True,
                help_text="Used to identify related NOFO types or templates, if applicable.",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Activity code",
            ),
        ),
        migrations.AddField(
            model_name="contentguideinstance",
            name="author",
            field=models.TextField(
                blank=True,
                help_text="Request your subagency name (e.g., OPHDST) instead of CDC as the author. (Optional)",
                verbose_name="NOFO author",
            ),
        ),
        migrations.AddField(
            model_name="contentguideinstance",
            name="federal_assistance_listing",
            field=models.CharField(
                blank=True,
                help_text="Associated assistance listing for this program.",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Federal assistance listing",
            ),
        ),
        migrations.AddField(
            model_name="contentguideinstance",
            name="keywords",
            field=models.TextField(
                blank=True,
                help_text="Suggest keywords to help someone get the overall sense of this opportunity. Provide 5 to 10 keywords, separate them by commas. (Optional)",
                verbose_name="NOFO keywords",
            ),
        ),
        migrations.AddField(
            model_name="contentguideinstance",
            name="statutory_authority",
            field=models.CharField(
                blank=True,
                help_text="Primary authority or legislation governing this program’s funding.",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Statutory authority",
            ),
        ),
        migrations.AddField(
            model_name="contentguideinstance",
            name="subject",
            field=models.TextField(
                blank=True,
                help_text='Add a one-line statement, 25 words or less. eg: "A notice of funding opportunity from the [Agency or OpDiv] about/on/to [the purpose of the NOFO]." (Optional).',
                verbose_name="NOFO subject",
            ),
        ),
        migrations.AddField(
            model_name="contentguideinstance",
            name="tagline",
            field=models.TextField(
                blank=True,
                help_text="A short phrase that describes your program. Leave blank if not known.",
                verbose_name="NOFO tagline",
            ),
        ),
    ]
