# Generated by Django 5.2.9 on 2025-12-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0007_contentguideinstance_activity_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentguidesubsection",
            name="status",
            field=models.CharField(
                choices=[
                    ("default", "Not started"),
                    ("viewed", "Viewed at least once"),
                    ("done", "Done editing"),
                ],
                default="default",
                help_text="Subsection progress status field used by NOFO Writers.Only relevant for subsections that belong to a ContentGuideInstance.",
                max_length=16,
            ),
        ),
    ]
