# Generated by Django 5.2.9 on 2025-12-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0008_contentguidesubsection_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentguidesubsection",
            name="enabled",
        ),
    ]
