# Generated by Django 5.2.7 on 2025-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0009_remove_contentguidesubsection_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentguidesubsection",
            name="variables",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Variables from the subsection body, keyed by variable key. If ContentGuideInstance, also includes writer-provided values.",
            ),
        ),
    ]
