# Generated by Django 5.2.7 on 2025-12-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composer", "0010_contentguidesubsection_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentguidesubsection",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="If optional, whether the subsection is currently hidden by the NOFO Writer.",
            ),
        ),
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="optional",
            field=models.BooleanField(
                default=False,
                help_text="Decide if this subsection is required, or can be hidden by NOFO Writers",
            ),
        ),
    ]
