# Generated by Django 4.2.7 on 2023-11-14 05:00

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nofo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True)),
                ("short_name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("order", models.IntegerField(null=True)),
                (
                    "nofo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="nofos.nofo",
                    ),
                ),
            ],
            options={
                "unique_together": {("nofo", "order")},
            },
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("order", models.IntegerField(null=True)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("h2", "Heading 2"),
                            ("h3", "Heading 3"),
                            ("h4", "Heading 4"),
                            ("h5", "Heading 5"),
                            ("h6", "Heading 6"),
                        ],
                        max_length=2,
                    ),
                ),
                ("body", martor.models.MartorField(blank=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nofos.section"
                    ),
                ),
            ],
            options={
                "unique_together": {("section", "order")},
            },
        ),
    ]
