# Generated by Django 4.2.7 on 2023-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0002_alter_nofo_short_name_alter_nofo_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="html_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="subsection",
            name="html_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
