# Generated by Django 4.2.7 on 2023-11-18 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0005_alter_nofo_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
