# Generated by Django 4.2.7 on 2023-12-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0006_nofo_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="The official number for this NOFO. It will be public.",
                max_length=200,
            ),
        ),
    ]
