# Generated by Django 4.2.7 on 2023-12-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0007_nofo_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="The official number for this NOFO. It will be public.",
                max_length=200,
                verbose_name="Opportunity number",
            ),
        ),
    ]
