# Generated by Django 4.2.9 on 2024-01-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0016_alter_nofo_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="theme",
            field=models.CharField(
                choices=[
                    ("landscape-cdc-blue", "CDC (Blue)"),
                    ("landscape-cdc-white", "CDC (White)"),
                    ("portrait-hrsa-blue", "HRSA (Blue)"),
                    ("portrait-hrsa-white", "HRSA (White)"),
                    ("portrait-acf-blue", "ACF (Blue)"),
                ],
                default="portrait-hrsa-blue",
                help_text="The theme sets the orientation and colour pallete for this NOFO.",
                max_length=32,
            ),
        ),
    ]
