# Generated by Django 4.2.9 on 2024-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0017_alter_nofo_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="application_deadline",
            field=models.TextField(
                blank=True,
                help_text="The date that applications for this NOFO must be submitted.",
                verbose_name="Application deadline",
            ),
        ),
    ]
