# Generated by Django 4.2.9 on 2024-01-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0018_nofo_application_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="application_deadline",
            field=models.CharField(
                blank=True,
                help_text="The date that applications for this NOFO must be submitted.",
                max_length=200,
                verbose_name="Application deadline",
            ),
        ),
    ]
