# Generated by Django 4.2.9 on 2024-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0020_alter_subsection_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="agency",
            field=models.CharField(
                blank=True,
                help_text="The agency within the operating division (eg, Bureau of Health Workforce)",
                max_length=511,
                verbose_name="Agency",
            ),
        ),
        migrations.AddField(
            model_name="nofo",
            name="opdiv",
            field=models.CharField(
                blank=True,
                help_text="The HHS operating division (eg, HRSA, CDC)",
                max_length=511,
                verbose_name="Operating Division",
            ),
        ),
        migrations.AddField(
            model_name="nofo",
            name="subagency",
            field=models.CharField(
                blank=True,
                help_text="The subagency within the agency (eg, Division of Medicine and Dentistry)",
                max_length=511,
                verbose_name="Subagency",
            ),
        ),
    ]
