# Generated by Django 4.2.9 on 2024-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0021_nofo_agency_nofo_opdiv_nofo_subagency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsection",
            name="name",
            field=models.TextField(blank=True, verbose_name="Subsection name"),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("h2", "Heading 2"),
                    ("h3", "Heading 3"),
                    ("h4", "Heading 4"),
                    ("h5", "Heading 5"),
                    ("h6", "Heading 6"),
                    ("h7", "Heading 7"),
                ],
                max_length=2,
            ),
        ),
    ]
