# Generated by Django 4.2.9 on 2024-01-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0022_alter_subsection_name_alter_subsection_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="coach",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emily", "Emily"),
                    ("hannah", "Hannah"),
                    ("julie", "Julie"),
                    ("july", "July"),
                    ("laura", "Laura"),
                    ("moira", "Moira"),
                    ("morgan", "Morgan"),
                ],
                help_text="The coach has the primary responsibility for editing this NOFO.",
                max_length=16,
            ),
        ),
    ]
