# Generated by Django 4.2.9 on 2024-01-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0027_alter_nofo_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("published", "Published"),
                ],
                default="draft",
                help_text="The status of this NOFO in the NOFO builder.",
                max_length=32,
            ),
        ),
    ]
