# Generated by Django 4.2.9 on 2024-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0028_nofo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="author",
            field=models.TextField(
                blank=True, help_text="Who wrote this NOFO.", verbose_name="NOFO author"
            ),
        ),
        migrations.AddField(
            model_name="nofo",
            name="keywords",
            field=models.TextField(
                blank=True,
                help_text="keywords for the NOFO.",
                verbose_name="NOFO keywords",
            ),
        ),
        migrations.AddField(
            model_name="nofo",
            name="subject",
            field=models.TextField(
                blank=True,
                help_text="What this NOFO about.",
                verbose_name="NOFO subject",
            ),
        ),
    ]
