# Generated by Django 4.2.9 on 2024-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0035_nofo_subagency2"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsection",
            name="html_class",
            field=models.CharField(
                blank=True, max_length=1023, verbose_name="HTML class attribute"
            ),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="html_id",
            field=models.CharField(
                blank=True, max_length=511, verbose_name="HTML id attribute"
            ),
        ),
    ]
