# Generated by Django 4.2.9 on 2024-02-06 17:11

from django.db import migrations


def transfer_page_break_to_class(apps, schema_editor):
    Subsection = apps.get_model("nofos", "Subsection")
    for subsection in Subsection.objects.all():
        if subsection.has_page_break:
            subsection.html_class += "page-break-before"  # Append class
            subsection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0036_subsection_html_class_alter_subsection_html_id"),
    ]

    operations = [
        migrations.RunPython(transfer_page_break_to_class),
    ]
