# Generated by Django 4.2.9 on 2024-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0038_remove_subsection_has_page_break"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="theme",
            field=models.CharField(
                choices=[
                    ("landscape-cdc-blue", "CDC Landscape (Default)"),
                    ("landscape-cdc-white", "CDC Landscape (Light)"),
                    ("landscape-cdc-dop", "CDC Landscape (DOP)"),
                    ("portrait-cdc-blue", "CDC Portrait (Default)"),
                    ("portrait-cdc-white", "CDC Portrait (Light)"),
                    ("portrait-hrsa-blue", "HRSA (Default)"),
                    ("portrait-hrsa-white", "HRSA (Light)"),
                    ("portrait-acf-blue", "ACF (Blue)"),
                    ("portrait-cms-white", "CMS (Light)"),
                ],
                default="portrait-hrsa-blue",
                help_text="The theme sets the orientation and colour pallete for this NOFO.",
                max_length=32,
            ),
        ),
    ]
