# Generated by Django 4.2.10 on 2024-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0056_alter_nofo_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
