# Generated by Django 4.2.10 on 2024-03-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0057_alter_nofo_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("ready_for_adam", "👀\xa0Adam"),
                    ("review", "In\xa0review"),
                    ("published", "Published"),
                ],
                default="draft",
                help_text="The status of this NOFO in the NOFO builder.",
                max_length=32,
            ),
        ),
    ]
