# Generated by Django 4.2.10 on 2024-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0066_alter_nofo_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="cover",
            field=models.CharField(
                choices=[
                    ("nofo--cover-page--hero", "Hero (large) image"),
                    ("nofo--cover-page--medium", "Small image"),
                    ("nofo--cover-page--text", "No image, large text"),
                ],
                default="nofo--cover-page--medium",
                help_text="The cover style for the NOFO.",
                max_length=32,
            ),
        ),
    ]
