# Generated by Django 4.2.14 on 2024-07-25 16:11

from django.db import migrations


def update_designer_field(apps, schema_editor):
    Nofo = apps.get_model("nofos", "Nofo")
    designer_mapping = {
        "adam": "bloom-adam",
        "emily": "bloom-emily",
        "kevin": "bloom-kevin",
        "yasmine": "bloom-yasmine",
    }

    for nofo in Nofo.objects.all():
        if nofo.designer in designer_mapping:
            nofo.designer = designer_mapping[nofo.designer]
            nofo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0068_alter_nofo_designer"),
    ]

    operations = [
        migrations.RunPython(update_designer_field),
    ]
