# Generated by Django 5.0.8 on 2024-10-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0071_nofo_cover_image_nofo_cover_image_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="coach",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aarti", "Aarti"),
                    ("alex", "Alex"),
                    ("emily", "Emily"),
                    ("hannah", "Hannah"),
                    ("idit", "Idit"),
                    ("julie", "Julie"),
                    ("july", "July"),
                    ("moira", "Moira"),
                    ("morgan", "Morgan"),
                    ("shane", "Shane"),
                ],
                help_text="The coach has the primary responsibility for editing this NOFO.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bloom-abbey", "Abbey"),
                    ("bloom-adam", "Adam"),
                    ("bloom-emily-b", "Emily\xa0B"),
                    ("bloom-emily-i", "Emily\xa0I"),
                    ("bloom-jackie", "Jackie"),
                    ("bloom-kevin", "Kevin"),
                    ("bloom-yasmine", "Yasmine"),
                    ("hrsa-betty", "Betty"),
                    ("hrsa-doretha", "Doretha"),
                    ("hrsa-gwen", "Gwen"),
                    ("hrsa-randy", "Randy"),
                    ("hrsa-stephanie", "Stephanie"),
                ],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("ready-for-adam", "👀\xa0Adam"),
                    ("review", "In\xa0review"),
                    ("published", "Published"),
                ],
                default="draft",
                help_text="The status of this NOFO in the NOFO builder.",
                max_length=32,
            ),
        ),
    ]
