# Generated by Django 5.0.8 on 2024-11-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0073_update_print_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("ready-for-qa", "Ready\xa0for\xa0QA"),
                    ("review", "In\xa0review"),
                    ("published", "Published"),
                ],
                default="draft",
                help_text="The status of this NOFO in the NOFO builder.",
                max_length=32,
            ),
        ),
    ]
