# Generated by Django 5.0.8 on 2024-11-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0075_alter_nofo_cover_alter_nofo_icon_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="The official opportunity number for this NOFO.",
                max_length=200,
                verbose_name="Opportunity number",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="A name that makes it easier to find this NOFO in a list. It won’t be public.",
                max_length=511,
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("ready-for-qa", "Ready\xa0for\xa0QA"),
                    ("review", "In\xa0review"),
                    ("published", "Published"),
                ],
                default="draft",
                help_text="The status of this NOFO in the NOFO Builder.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="The official name for this NOFO. It will be public when the NOFO is published.",
                verbose_name="NOFO title",
            ),
        ),
    ]
