# Generated by Django 5.0.8 on 2024-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0080_alter_nofo_coach_alter_nofo_designer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="The filename used to import this NOFO. If re-imported, this value is the most recent filename.",
                max_length=511,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="inline_css",
            field=models.TextField(
                blank=True,
                help_text="Extra CSS to include for this specific NOFO.",
                null=True,
                verbose_name="Inline CSS",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="subagency2",
            field=models.CharField(
                blank=True,
                help_text="Another subagency within the agency (eg, Division of Medicine and Dentistry) collaborating on this NOFO",
                max_length=511,
                null=True,
                verbose_name="Subagency 2",
            ),
        ),
    ]
