# Generated by Django 5.0.8 on 2024-12-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0081_alter_nofo_filename_alter_nofo_inline_css_and_more"),
        ("nofos", "0081_alter_nofo_theme"),
    ]

    operations = []
