# Generated by Django 5.0.8 on 2024-12-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0082_merge_20241218_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="group",
            field=models.CharField(
                choices=[
                    ("bloom", "Bloomworks"),
                    ("acf", "ACF: Administration for Children and Families"),
                    ("acl", "ACL: Administration for Community Living"),
                    (
                        "aspr",
                        "ASPR: Administration for Strategic Preparedness and Response",
                    ),
                    ("cdc", "CDC: Centers for Disease Control and Prevention"),
                    ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                    ("hrsa", "HRSA: Health Resources and Services Administration"),
                    ("ihs", "IHS: Indian Health Service"),
                    ("staging", "Staging environment"),
                ],
                default="bloom",
                help_text="The OpDiv grouping of this NOFO. The group is used to control access to a NOFO.",
                max_length=16,
            ),
        ),
    ]
