# Generated by Django 5.0.8 on 2025-01-10 02:41

from django.db import migrations
from django.utils.text import slugify


def populate_required_fields(apps, schema_editor):
    Section = apps.get_model("nofos", "Section")

    # Fix sections with empty names
    for section in Section.objects.filter(name=""):
        section.name = f"Untitled Section {section.order or 'Unknown'}"
        section.save()

    # Fix sections with empty html_ids
    for section in Section.objects.filter(html_id=""):
        # Create an html_id in the format: "{order}--{slugified-name}"
        order = section.order or 0
        slugified_name = slugify(section.name)
        section.html_id = f"{order}--{slugified_name}"
        section.save()


def reverse_populate(apps, schema_editor):
    # No reverse migration needed
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0083_alter_nofo_group"),
    ]

    operations = [
        migrations.RunPython(populate_required_fields, reverse_populate),
    ]
