# Generated by Django 5.0.8 on 2025-01-10 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0085_update_model_fields_and_validators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="html_id",
            field=models.CharField(
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.TextField(
                max_length=250,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name="Section name",
            ),
        ),
    ]
