# Generated by Django 5.0.8 on 2025-01-10 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0086_alter_section_html_id_alter_section_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bloom-abbey", "Abbey"),
                    ("bloom-adam", "Adam"),
                    ("bloom-emily-b", "Emily\xa0B"),
                    ("bloom-emily-i", "Emily\xa0I"),
                    ("bloom-jackie", "Jackie"),
                    ("bloom-jana", "Jana"),
                    ("bloom-kevin", "Kevin"),
                    ("bloom-yasmine", "Yasmine"),
                    ("hrsa-betty", "Betty"),
                    ("hrsa-doretha", "Doretha"),
                    ("hrsa-ericka", "Ericka"),
                    ("hrsa-gwen", "Gwen"),
                    ("hrsa-jene", "Jene"),
                    ("hrsa-kieumy", "KieuMy"),
                    ("hrsa-lynda", "Lynda"),
                    ("hrsa-randy", "Randy"),
                    ("hrsa-shonda", "Shonda"),
                    ("hrsa-stephanie", "Stephanie\xa0V"),
                ],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
    ]
