# Generated by Django 5.0.13 on 2025-05-05 19:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0100_populate_uuids_nofos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
