# Generated by Django 5.0.13 on 2025-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0101_alter_nofo_uuid_alter_section_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="successor",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="nofo",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="section",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
