# Generated by Django 5.0.13 on 2025-05-07 22:18
from django.db import connection, migrations


def promote_uuid_to_id_nofos(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        sql = """
            -- PostgreSQL: Update ID to UUID for nofos
            UPDATE nofos_nofo SET id = uuid;
            UPDATE nofos_section SET id = uuid;
            UPDATE nofos_subsection SET id = uuid;
        """
        with connection.cursor() as cursor:
            cursor.execute(sql)

    elif db_vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute("UPDATE nofos_nofo SET id = uuid;")
            cursor.execute("UPDATE nofos_section SET id = uuid;")
            cursor.execute("UPDATE nofos_subsection SET id = uuid;")

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0106_alter_nofo_id_alter_section_id_alter_subsection_id"),
    ]

    operations = [
        migrations.RunPython(promote_uuid_to_id_nofos),
    ]
