# Generated by Django 5.0.13 on 2025-05-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0107_nofos_copy_uuid_to_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ancestors",
                to="nofos.nofo",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="nofo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="nofos.nofo",
            ),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsections",
                to="nofos.section",
            ),
        ),
    ]
