# Generated by Django 4.2.7 on 2023-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='questions',
        ),
        migrations.AlterField(
            model_name='overview',
            name='cost_share_or_match_requirement',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='overview',
            name='eligible_applications',
            field=models.TextField(),
        ),
    ]
