# Generated by Django 4.2.7 on 2023-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_overview_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='application_deadline',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='overview',
            name='cost_share_or_match_requirement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='expected_funding_per_recipient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='overview',
            name='performance_period',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
