# Generated by Django 4.2.7 on 2023-11-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_overview_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shortTitle',
            field=models.CharField(default='short title', max_length=256, verbose_name='short title'),
        ),
        migrations.AddField(
            model_name='overview',
            name='questions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='summary',
            field=models.TextField(default='summary'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='overview',
            name='application_deadline',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='overview',
            name='expected_awards',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='overview',
            name='expected_funding',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='overview',
            name='nofo_type',
            field=models.CharField(max_length=128, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='performance_period',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=128)),
                ('officeOrBureau', models.CharField(max_length=128)),
                ('division', models.CharField(max_length=128)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
    ]
