# Generated by Django 4.2.7 on 2023-11-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_shorttitle_overview_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='shortTitle',
            field=models.CharField(max_length=256, verbose_name='short title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='division',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='overview',
            name='summary',
            field=models.TextField(),
        ),
    ]
