from django.urls import path

from . import views
from .models import ContentGuide

app_name = "composer"

urlpatterns = [
    path("", views.ComposerListView.as_view(), name="composer_index"),
    path("import", views.ComposerImportView.as_view(), name="composer_import"),
    path(
        "<uuid:pk>/import/title",
        views.ComposerImportTitleView.as_view(),
        name="composer_import_title",
    ),
    path(
        "<uuid:pk>/delete", views.ComposerArchiveView.as_view(), name="composer_archive"
    ),
    path(
        "<uuid:pk>/history",
        views.ComposerHistoryView.as_view(),
        name="composer_history",
    ),
    path(
        "<uuid:pk>",
        views.composer_section_redirect,
        name="composer_document_redirect",
    ),
    path(
        "<uuid:pk>/edit/title",
        views.ComposerEditTitleView.as_view(),
        name="composer_edit_title",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>",
        views.ComposerSectionView.as_view(),
        name="section_view",
    ),
    path(
        "<uuid:pk>/preview",
        views.ComposerPreviewView.as_view(),
        name="composer_preview",
    ),
    path(
        "<uuid:pk>/unpublish",
        views.ComposerUnpublishView.as_view(),
        name="composer_unpublish",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/edit",
        views.ComposerSectionEditView.as_view(),
        name="section_edit",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/subsection/create",
        views.ComposerSubsectionCreateView.as_view(),
        name="subsection_create",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/subsection/<uuid:subsection_pk>/edit",
        views.ComposerSubsectionEditView.as_view(),
        name="subsection_edit",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/subsection/<uuid:subsection_pk>/delete",
        views.ComposerSubsectionDeleteView.as_view(),
        name="subsection_confirm_delete",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/subsection/<uuid:subsection_pk>/instructions/edit",
        views.ComposerSubsectionInstructionsEditView.as_view(),
        name="instructions_edit",
    ),
    # WRITER FLOW URLS
    path(
        "writer",
        views.WriterDashboardView.as_view(),
        name="writer_index",
    ),
    path(
        "writer/before-start",
        views.WriterInstanceBeforeStartView.as_view(),
        name="writer_before_start",
    ),
    path(
        "writer/start",
        views.WriterInstanceStartView.as_view(),
        name="writer_start",
    ),
    path(
        "writer/start/<uuid:parent_pk>/details",
        views.WriterInstanceDetailsView.as_view(),
        name="writer_details",
    ),
    path(
        "writer/<uuid:pk>/conditional-questions/<int:page>",
        views.WriterInstanceConditionalQuestionView.as_view(),
        name="writer_conditional_questions",
    ),
    path(
        "writer/<uuid:pk>/confirmation",
        views.WriterInstanceConfirmationView.as_view(),
        name="writer_confirmation",
    ),
    path(
        "writer/<uuid:pk>",
        views.writer_instance_redirect,
        name="writer_instance_redirect",
    ),
    path(
        "writer/<uuid:pk>/delete",
        views.WriterInstanceArchiveView.as_view(),
        name="writer_archive",
    ),
    path(
        "writer/<uuid:pk>/section/<uuid:section_pk>",
        views.ComposerSectionView.as_view(),
        name="writer_section_view",
    ),
    path(
        "writer/<uuid:pk>/section/<uuid:section_pk>/subsection/<uuid:subsection_pk>/edit",
        views.WriterInstanceSubsectionEditView.as_view(),
        name="writer_subsection_edit",
    ),
    path(
        "writer/<uuid:pk>/preview",
        views.WriterInstancePreviewView.as_view(),
        name="writer_preview",
    ),
    path(
        "writer/<uuid:pk>/history",
        views.WriterInstanceHistoryView.as_view(),
        name="writer_instance_history",
    ),
    path(
        # NOTE: 'compare' cannot be in the URL path so that header links from base.html work correctly
        "writer/<uuid:pk>/history/<int:event_id>",
        views.WriterInstanceHistoryCompareView.as_view(),
        name="writer_instance_history_compare",
    ),
]
