# Generated by Django 5.0.13 on 2025-04-09 21:16

import django.core.validators
import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0001_initial"),
        ("nofos", "0097_alter_section_options_alter_subsection_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGuideSubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, max_length=400, verbose_name="Subsection name"
                    ),
                ),
                (
                    "html_id",
                    models.CharField(
                        blank=True,
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                        verbose_name="HTML id attribute",
                    ),
                ),
                (
                    "html_class",
                    models.CharField(
                        blank=True,
                        max_length=1023,
                        validators=[django.core.validators.MaxLengthValidator(1023)],
                        verbose_name="HTML class attribute",
                    ),
                ),
                ("order", models.IntegerField(null=True)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("h2", "Heading 2"),
                            ("h3", "Heading 3"),
                            ("h4", "Heading 4"),
                            ("h5", "Heading 5"),
                            ("h6", "Heading 6"),
                            ("h7", "Heading 7"),
                        ],
                        max_length=2,
                        validators=[django.core.validators.MaxLengthValidator(2)],
                    ),
                ),
                (
                    "callout_box",
                    models.BooleanField(
                        default=False,
                        help_text="Make this subsection a callout box.",
                        verbose_name="Callout box",
                    ),
                ),
                (
                    "body",
                    martor.models.MartorField(
                        blank=True, verbose_name="Content of subsection"
                    ),
                ),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("none", "Do not compare"),
                            ("name", "Compare name"),
                            ("body", "Compare name and all text"),
                            ("diff_strings", "Compare name and text segments"),
                        ],
                        default="name",
                        max_length=20,
                    ),
                ),
                (
                    "diff_strings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required strings that must be present in the body.",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diff_subsections",
                        to="nofos.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("section", "order")},
            },
        ),
    ]
