# Generated by Django 5.0.13 on 2025-05-07 22:02
from django.db import connection, migrations


def clean_easyaudit_deleted_guides(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                """
                DELETE FROM easyaudit_crudevent 
                WHERE object_json_repr LIKE '%"model": "guides.contentguide"%'
                AND object_id::bigint NOT IN (SELECT id FROM guides_contentguide);
                """
            )
            cursor.execute(
                """
                DELETE FROM easyaudit_crudevent 
                WHERE object_json_repr LIKE '%"model": "guides.contentguidesection"%'
                AND object_id::bigint NOT IN (SELECT id FROM guides_contentguidesection);
                """
            )
            cursor.execute(
                """
                DELETE FROM easyaudit_crudevent 
                WHERE object_json_repr LIKE '%"model": "guides.contentguidesubsection"%'
                AND object_id::bigint NOT IN (SELECT id FROM guides_contentguidesubsection);
                """
            )

    elif db_vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute(
                """
                DELETE FROM easyaudit_crudevent 
                WHERE object_json_repr LIKE '%"model": "guides.contentguide"%'
                AND object_id NOT IN (SELECT CAST(id AS TEXT) FROM guides_contentguide);
            """
            )
            cursor.execute(
                """
                DELETE FROM easyaudit_crudevent 
                WHERE object_json_repr LIKE '%"model": "guides.contentguidesection"%'
                AND object_id NOT IN (SELECT CAST(id AS TEXT) FROM guides_contentguidesection);
            """
            )
            cursor.execute(
                """
                DELETE FROM easyaudit_crudevent 
                WHERE object_json_repr LIKE '%"model": "guides.contentguidesubsection"%'
                AND object_id NOT IN (SELECT CAST(id AS TEXT) FROM guides_contentguidesubsection);
            """
            )

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0009_guides_update_foreign_keys_to_uuid"),
    ]

    operations = [
        migrations.RunPython(clean_easyaudit_deleted_guides),
    ]
