# Generated by Django 5.0.13 on 2025-05-07 22:06
from django.db import connection, migrations


def update_easyaudit_guides_to_uuid(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        sql = """
            -- PostgreSQL: Update ContentGuide IDs in EasyAudit to UUIDs with quoted UUIDs in JSON
            UPDATE easyaudit_crudevent
            SET object_id = g.uuid::text,
                object_json_repr = REGEXP_REPLACE(object_json_repr, '"pk": \\d+', '"pk": "' || g.uuid || '"', 'g')
            FROM guides_contentguide g
            WHERE easyaudit_crudevent.object_json_repr LIKE '%"model": "guides.contentguide"%'
            AND CAST(easyaudit_crudevent.object_id AS INTEGER) = g.id;

            -- ContentGuideSections
            UPDATE easyaudit_crudevent
            SET object_id = gs.uuid::text,
                object_json_repr = REGEXP_REPLACE(object_json_repr, '"pk": \\d+', '"pk": "' || gs.uuid || '"', 'g')
            FROM guides_contentguidesection gs
            WHERE easyaudit_crudevent.object_json_repr LIKE '%"model": "guides.contentguidesection"%'
            AND CAST(easyaudit_crudevent.object_id AS INTEGER) = gs.id;

            -- ContentGuideSubsections
            UPDATE easyaudit_crudevent
            SET object_id = gss.uuid::text,
                object_json_repr = REGEXP_REPLACE(object_json_repr, '"pk": \\d+', '"pk": "' || gss.uuid || '"', 'g')
            FROM guides_contentguidesubsection gss
            WHERE easyaudit_crudevent.object_json_repr LIKE '%"model": "guides.contentguidesubsection"%'
            AND CAST(easyaudit_crudevent.object_id AS INTEGER) = gss.id;
        """
        with connection.cursor() as cursor:
            cursor.execute(sql)

    elif db_vendor == "sqlite":
        with connection.cursor() as cursor:
            # ContentGuide
            cursor.execute(
                """
                UPDATE easyaudit_crudevent 
                SET object_id = (
                    SELECT
                        SUBSTR(uuid, 1, 8) || '-' ||
                        SUBSTR(uuid, 9, 4) || '-' ||
                        SUBSTR(uuid, 13, 4) || '-' ||
                        SUBSTR(uuid, 17, 4) || '-' ||
                        SUBSTR(uuid, 21)
                    FROM guides_contentguide WHERE CAST(object_id AS INTEGER) = id
                ),
                object_json_repr = REPLACE(
                    object_json_repr,
                    '"pk": ' || object_id,
                    '"pk": "' ||
                    SUBSTR((SELECT uuid FROM guides_contentguide WHERE CAST(object_id AS INTEGER) = id), 1, 8) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguide WHERE CAST(object_id AS INTEGER) = id), 9, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguide WHERE CAST(object_id AS INTEGER) = id), 13, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguide WHERE CAST(object_id AS INTEGER) = id), 17, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguide WHERE CAST(object_id AS INTEGER) = id), 21)
                    || '"'
                )
                WHERE object_json_repr LIKE '%"model": "guides.contentguide"%';
                """
            )

            # ContentGuideSections
            cursor.execute(
                """
                UPDATE easyaudit_crudevent 
                SET object_id = (
                    SELECT
                        SUBSTR(uuid, 1, 8) || '-' ||
                        SUBSTR(uuid, 9, 4) || '-' ||
                        SUBSTR(uuid, 13, 4) || '-' ||
                        SUBSTR(uuid, 17, 4) || '-' ||
                        SUBSTR(uuid, 21)
                    FROM guides_contentguidesection WHERE CAST(object_id AS INTEGER) = id
                ),
                object_json_repr = REPLACE(
                    object_json_repr,
                    '"pk": ' || object_id,
                    '"pk": "' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesection WHERE CAST(object_id AS INTEGER) = id), 1, 8) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesection WHERE CAST(object_id AS INTEGER) = id), 9, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesection WHERE CAST(object_id AS INTEGER) = id), 13, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesection WHERE CAST(object_id AS INTEGER) = id), 17, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesection WHERE CAST(object_id AS INTEGER) = id), 21)
                    || '"'
                )
                WHERE object_json_repr LIKE '%"model": "guides.contentguidesection"%';
                """
            )

            # ContentGuideSubsections
            cursor.execute(
                """
                UPDATE easyaudit_crudevent 
                SET object_id = (
                    SELECT
                        SUBSTR(uuid, 1, 8) || '-' ||
                        SUBSTR(uuid, 9, 4) || '-' ||
                        SUBSTR(uuid, 13, 4) || '-' ||
                        SUBSTR(uuid, 17, 4) || '-' ||
                        SUBSTR(uuid, 21)
                    FROM guides_contentguidesubsection WHERE CAST(object_id AS INTEGER) = id
                ),
                object_json_repr = REPLACE(
                    object_json_repr,
                    '"pk": ' || object_id,
                    '"pk": "' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesubsection WHERE CAST(object_id AS INTEGER) = id), 1, 8) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesubsection WHERE CAST(object_id AS INTEGER) = id), 9, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesubsection WHERE CAST(object_id AS INTEGER) = id), 13, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesubsection WHERE CAST(object_id AS INTEGER) = id), 17, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM guides_contentguidesubsection WHERE CAST(object_id AS INTEGER) = id), 21)
                    || '"'
                )
                WHERE object_json_repr LIKE '%"model": "guides.contentguidesubsection"%';
                """
            )

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0010_guides_clean_easyaudit_records_for_deleted_objects"),
    ]

    operations = [
        migrations.RunPython(update_easyaudit_guides_to_uuid),
    ]
