# Generated by Django 5.0.13 on 2025-05-07 21:15

import uuid

from django.db import connection, migrations, models


def promote_uuid_to_id_guides(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        with connection.cursor() as cursor:
            # Step 1: Create a temp UUID column and populate it with existing UUID values
            cursor.execute("ALTER TABLE guides_contentguide ADD COLUMN temp_id UUID;")
            cursor.execute("UPDATE guides_contentguide SET temp_id = uuid;")

            cursor.execute(
                "ALTER TABLE guides_contentguidesection ADD COLUMN temp_id UUID;"
            )
            cursor.execute("UPDATE guides_contentguidesection SET temp_id = uuid;")

            cursor.execute(
                "ALTER TABLE guides_contentguidesubsection ADD COLUMN temp_id UUID;"
            )
            cursor.execute("UPDATE guides_contentguidesubsection SET temp_id = uuid;")

            # Step 2: Dynamically fetch and drop primary key constraints
            cursor.execute(
                """
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name='guides_contentguide' 
                AND constraint_type='PRIMARY KEY';
                """
            )
            guide_pkey = cursor.fetchone()[0]
            cursor.execute(
                f"ALTER TABLE guides_contentguide DROP CONSTRAINT {guide_pkey};"
            )

            cursor.execute(
                """
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name='guides_contentguidesection' 
                AND constraint_type='PRIMARY KEY';
                """
            )
            section_pkey = cursor.fetchone()[0]
            cursor.execute(
                f"ALTER TABLE guides_contentguidesection DROP CONSTRAINT {section_pkey};"
            )

            cursor.execute(
                """
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name='guides_contentguidesubsection' 
                AND constraint_type='PRIMARY KEY';
                """
            )
            subsection_pkey = cursor.fetchone()[0]
            cursor.execute(
                f"ALTER TABLE guides_contentguidesubsection DROP CONSTRAINT {subsection_pkey};"
            )

            # Step 3: Rename temp_id to id, and make it the primary key
            cursor.execute("ALTER TABLE guides_contentguide DROP COLUMN id;")
            cursor.execute(
                "ALTER TABLE guides_contentguide RENAME COLUMN temp_id TO id;"
            )
            cursor.execute("ALTER TABLE guides_contentguide ADD PRIMARY KEY (id);")

            cursor.execute("ALTER TABLE guides_contentguidesection DROP COLUMN id;")
            cursor.execute(
                "ALTER TABLE guides_contentguidesection RENAME COLUMN temp_id TO id;"
            )
            cursor.execute(
                "ALTER TABLE guides_contentguidesection ADD PRIMARY KEY (id);"
            )

            cursor.execute("ALTER TABLE guides_contentguidesubsection DROP COLUMN id;")
            cursor.execute(
                "ALTER TABLE guides_contentguidesubsection RENAME COLUMN temp_id TO id;"
            )
            cursor.execute(
                "ALTER TABLE guides_contentguidesubsection ADD PRIMARY KEY (id);"
            )

    elif db_vendor == "sqlite":
        pass

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0011_guides_easyaudit_uuid"),
    ]

    operations = [
        migrations.RunPython(promote_uuid_to_id_guides),
        migrations.AlterField(
            model_name="contentguide",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentguidesection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
