# Generated by Django 5.2.3 on 2025-07-21 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0018_alter_contentguide_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentguidesection",
            name="html_class",
            field=models.CharField(
                blank=True,
                max_length=1023,
                validators=[django.core.validators.MaxLengthValidator(1023)],
                verbose_name="HTML class attribute",
            ),
        ),
    ]
