# Generated by Django 5.2.3 on 2025-07-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0020_alter_contentguidesection_html_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="comparison_type",
            field=models.CharField(
                choices=[
                    ("none", "Do not compare"),
                    ("name", "Compare name"),
                    ("body", "Compare name and all text"),
                    ("diff_strings", "Compare name and required strings"),
                ],
                default="body",
                max_length=20,
            ),
        ),
    ]
