# Generated by Django 5.2.3 on 2025-08-06 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0021_alter_contentguidesubsection_comparison_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguide",
            name="title",
            field=models.TextField(
                blank=True,
                max_length=250,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name="Content guide name",
            ),
        ),
    ]
