# Generated by Django 5.2.5 on 2025-08-21 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0022_alter_contentguide_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguide",
            name="group",
            field=models.CharField(
                choices=[
                    ("bloom", "Bloomworks"),
                    ("acf", "ACF: Administration for Children and Families"),
                    ("acl", "ACL: Administration for Community Living"),
                    (
                        "aspr",
                        "ASPR: Administration for Strategic Preparedness and Response",
                    ),
                    ("cdc", "CDC: Centers for Disease Control and Prevention"),
                    ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                    ("hrsa", "HRSA: Health Resources and Services Administration"),
                    ("ihs", "IHS: Indian Health Service"),
                    ("staging", "Staging environment"),
                ],
                default="bloom",
                help_text="The OpDiv group for this document. The group controls access to a document. The 'Bloomworks' group hides documents from OpDiv users.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
    ]
