# Generated by Django 5.2.6 on 2025-09-22 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0023_alter_contentguide_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentguide",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterField(
            model_name="contentguide",
            name="title",
            field=models.TextField(
                blank=True,
                max_length=250,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name="Document name",
            ),
        ),
    ]
