# Generated by Django 5.2.7 on 2025-10-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0024_alter_contentguide_options_alter_contentguide_title"),
        ("nofos", "0118_alter_nofo_designer"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentguide",
            name="from_nofo",
            field=models.ForeignKey(
                blank=True,
                help_text="If this guide was cloned from a NOFO, this is the source NOFO.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_guides",
                to="nofos.nofo",
            ),
        ),
    ]
