from django.urls import path

from . import views

app_name = "nofos"

urlpatterns = [
    path("", views.NofosListView.as_view(), name="nofo_index"),
    path("import", views.NofosImportNewView.as_view(), name="nofo_import"),
    path("<uuid:pk>/delete", views.NofosArchiveView.as_view(), name="nofo_archive"),
    path(
        "<uuid:pk>/history",
        views.NofoHistoryView.as_view(),
        name="nofo_history",
    ),
    path(
        "<uuid:pk>/history/<int:event_id>",
        views.NofoHistoryCompareView.as_view(),
        name="nofo_history_compare",
    ),
    path(
        "<uuid:pk>/history-modifications",
        views.NofoModificationsHistoryView.as_view(),
        name="nofo_history_modifications",
    ),
    path(
        "<uuid:pk>/duplicate",
        views.NofoDuplicateView.as_view(),
        name="nofo_duplicate",
    ),
    path(
        "<uuid:pk>/duplicate/title",
        views.NofoDuplicateTitleView.as_view(),
        name="nofo_duplicate_title",
    ),
    path(
        "<uuid:pk>/import",
        views.NofosImportOverwriteView.as_view(),
        name="nofo_import_overwrite",
    ),
    path(
        "<uuid:pk>/confirm-import/",
        views.NofosConfirmReimportView.as_view(),
        name="nofo_import_confirm_overwrite",
    ),
    path(
        "<uuid:pk>/import/title",
        views.NofoImportTitleView.as_view(),
        name="nofo_import_title",
    ),
    path(
        "<uuid:pk>/import/number",
        views.NofoImportNumberView.as_view(),
        name="nofo_import_number",
    ),
    path("<uuid:pk>", views.NofosDetailView.as_view(), name="nofo_view"),
    path("<uuid:pk>/export", views.NOFOsExportView.as_view(), name="nofo_export"),
    path("<uuid:pk>/edit", views.NofosEditView.as_view(), name="nofo_edit"),
    path(
        "<uuid:pk>/edit/coach-designer",
        views.NofoEditCoachDesignerView.as_view(),
        name="nofo_edit_coach_designer",
    ),
    path(
        "<uuid:pk>/edit/title",
        views.NofoEditTitleView.as_view(),
        name="nofo_edit_title",
    ),
    path(
        "<uuid:pk>/edit/short-name",
        views.NofoEditShortNameView.as_view(),
        name="nofo_edit_short_name",
    ),
    path(
        "<uuid:pk>/edit/number",
        views.NofoEditNumberView.as_view(),
        name="nofo_edit_number",
    ),
    path(
        "<uuid:pk>/edit/group",
        views.NofoEditGroupView.as_view(),
        name="nofo_edit_group",
    ),
    path(
        "<uuid:pk>/edit/application-deadline",
        views.NofoEditApplicationDeadlineView.as_view(),
        name="nofo_edit_application_deadline",
    ),
    path(
        "<uuid:pk>/edit/tagline",
        views.NofoEditTaglineView.as_view(),
        name="nofo_edit_tagline",
    ),
    path(
        "<uuid:pk>/edit/metadata",
        views.NofoEditMetadataView.as_view(),
        name="nofo_edit_metadata",
    ),
    path(
        "<uuid:pk>/edit/opdiv",
        views.NofoEditOpDivView.as_view(),
        name="nofo_edit_opdiv",
    ),
    path(
        "<uuid:pk>/edit/agency",
        views.NofoEditAgencyView.as_view(),
        name="nofo_edit_agency",
    ),
    path(
        "<uuid:pk>/edit/subagency",
        views.NofoEditSubagencyView.as_view(),
        name="nofo_edit_subagency",
    ),
    path(
        "<uuid:pk>/edit/subagency2",
        views.NofoEditSubagency2View.as_view(),
        name="nofo_edit_subagency2",
    ),
    path(
        "<uuid:pk>/edit/theme-options",
        views.NofoEditThemeOptionsView.as_view(),
        name="nofo_edit_theme_options",
    ),
    path(
        "<uuid:pk>/edit/cover-image",
        views.NofoEditCoverImageView.as_view(),
        name="nofo_edit_cover_image",
    ),
    path(
        "<uuid:pk>/upload/cover-image",
        views.NofoUploadCoverImageView.as_view(),
        name="nofo_upload_cover_image",
    ),
    path(
        "<uuid:pk>/delete/cover-image",
        views.NofoDeleteCoverImageView.as_view(),
        name="nofo_delete_cover_image",
    ),
    path(
        "<uuid:pk>/edit/status",
        views.NofoEditStatusView.as_view(),
        name="nofo_edit_status",
    ),
    path(
        "<uuid:pk>/edit/before-you-begin",
        views.NofoEditBeforeYouBeginPageView.as_view(),
        name="nofo_edit_byb",
    ),
    path(
        "<uuid:pk>/edit/modifications",
        views.NofoEditModificationView.as_view(),
        name="nofo_modifications",
    ),
    path("<uuid:pk>/print", views.PrintNofoAsPDFView.as_view(), name="print_pdf"),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/subsection/create",
        views.NofoSubsectionCreateView.as_view(),
        name="subsection_create",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>",
        views.NofoSectionDetailView.as_view(),
        name="section_detail",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/toggle-full-width-tables",
        views.SectionToggleTablesView.as_view(),
        name="section_toggle_tables",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/subsection/<uuid:subsection_pk>/edit",
        views.NofoSubsectionEditView.as_view(),
        name="subsection_edit",
    ),
    path(
        "<uuid:pk>/section/<uuid:section_pk>/subsection/<uuid:subsection_pk>/delete",
        views.NofoSubsectionDeleteView.as_view(),
        name="subsection_delete",
    ),
    path(
        "<uuid:pk>/check-links",
        views.CheckNOFOLinksDetailView.as_view(),
        name="nofo_check_links",
    ),
    path("search", views.NofoSearchView.as_view(), name="nofo_search"),
    path(
        "check-link",
        views.CheckNOFOLinkSingleView.as_view(),
        name="nofo_check_link_single",
    ),
    path(
        "<uuid:pk>/find-replace",
        views.NofoFindReplaceView.as_view(),
        name="nofo_find_replace",
    ),
    path(
        "<uuid:pk>/remove-page-breaks",
        views.NofoRemovePageBreaksView.as_view(),
        name="nofo_remove_page_breaks",
    ),
]
