# Generated by Django 5.0.13 on 2025-04-09 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="The filename used to import this document. If re-imported, this value is the most recent filename.",
                        max_length=511,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("bloom", "Bloomworks"),
                            ("acf", "ACF: Administration for Children and Families"),
                            ("acl", "ACL: Administration for Community Living"),
                            (
                                "aspr",
                                "ASPR: Administration for Strategic Preparedness and Response",
                            ),
                            ("cdc", "CDC: Centers for Disease Control and Prevention"),
                            ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                            (
                                "hrsa",
                                "HRSA: Health Resources and Services Administration",
                            ),
                            ("ihs", "IHS: Indian Health Service"),
                            ("staging", "Staging environment"),
                        ],
                        default="bloom",
                        help_text="The OpDiv grouping for this document. The group is used to control access to a NOFO. The 'Bloomworks' group can be used to hide NOFOs from OpDiv users.",
                        max_length=16,
                        validators=[django.core.validators.MaxLengthValidator(16)],
                    ),
                ),
                (
                    "opdiv",
                    models.CharField(
                        help_text="The HHS operating division (eg, HRSA, CDC)",
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                        verbose_name="Operating Division",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("ready-for-qa", "Ready\xa0for\xa0QA"),
                            ("review", "In\xa0review"),
                            ("published", "Published"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="The status of this document in the NOFO Builder.",
                        max_length=32,
                        validators=[django.core.validators.MaxLengthValidator(32)],
                    ),
                ),
                (
                    "archived",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="Archived documents are soft-deleted: they are not visible in the UI but can be recovered by superusers.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        help_text="The title of this Content Guide template.",
                        max_length=250,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name="Content Guide title",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestors",
                        to="guides.contentguide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Guide",
                "verbose_name_plural": "Content Guides",
            },
        ),
    ]
