# Generated by Django 5.0.13 on 2025-04-09 22:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_contentguidesubsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGuideSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=250,
                        validators=[django.core.validators.MaxLengthValidator(250)],
                        verbose_name="Section name",
                    ),
                ),
                (
                    "html_id",
                    models.CharField(
                        max_length=511,
                        validators=[django.core.validators.MaxLengthValidator(511)],
                    ),
                ),
                ("order", models.IntegerField(null=True)),
                (
                    "has_section_page",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this section will have its own page and icon in the ToC.",
                        verbose_name="Has section page?",
                    ),
                ),
                (
                    "content_guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="guides.contentguide",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsections",
                to="guides.contentguidesection",
            ),
        ),
    ]
