# Generated by Django 5.0.13 on 2025-05-05 19:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0006_populate_uuids_guides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguide",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="contentguidesection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
