# Generated by Django 5.0.13 on 2025-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0007_alter_contentguide_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguide",
            name="successor",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="contentguidesection",
            name="content_guide",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="section",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
