# Generated by Django 5.0.13 on 2025-05-07 20:31
from django.db import connection, migrations


def update_foreign_keys_to_uuid_guides(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        with connection.cursor() as cursor:
            # ContentGuide Successor
            cursor.execute(
                """
                UPDATE guides_contentguide AS g1
                SET successor = g2.uuid
                FROM guides_contentguide g2
                WHERE g1.successor IS NOT NULL 
                  AND g1.successor = g2.id::text;
                """
            )

            # ContentGuideSection Content Guide
            cursor.execute(
                """
                UPDATE guides_contentguidesection AS s
                SET content_guide = g.uuid
                FROM guides_contentguide g
                WHERE s.content_guide = g.id::text;
                """
            )

            # ContentGuideSubsection Section
            cursor.execute(
                """
                UPDATE guides_contentguidesubsection AS s
                SET section = g.uuid
                FROM guides_contentguidesection g
                WHERE s.section = g.id::text;
                """
            )

    elif db_vendor == "sqlite":
        with connection.cursor() as cursor:
            # Temporarily disable foreign key checks
            cursor.execute("PRAGMA foreign_keys=OFF;")

            # Split the SQLite queries into separate commands
            cursor.execute(
                """
                UPDATE guides_contentguide 
                SET successor = (
                    SELECT cg2.uuid 
                    FROM guides_contentguide cg2
                    WHERE cg2.id = guides_contentguide.successor
                )
                WHERE successor IS NOT NULL;
            """
            )
            cursor.execute(
                """
                UPDATE guides_contentguidesection 
                SET content_guide = (SELECT uuid FROM guides_contentguide WHERE id = content_guide);
            """
            )
            cursor.execute(
                """
                UPDATE guides_contentguidesubsection 
                SET section = (SELECT uuid FROM guides_contentguidesection WHERE id = section);
            """
            )

            # Re-enable foreign key checks
            cursor.execute("PRAGMA foreign_keys=ON;")

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0008_alter_contentguide_successor_and_more"),
    ]

    operations = [
        migrations.RunPython(update_foreign_keys_to_uuid_guides),
    ]
