# Generated by Django 5.0.13 on 2025-05-07 22:18
from django.db import connection, migrations


def promote_uuid_to_id_guides(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        sql = """
            -- PostgreSQL: Update ID to UUID for guides
            UPDATE guides_contentguide SET id = uuid;
            UPDATE guides_contentguidesection SET id = uuid;
            UPDATE guides_contentguidesubsection SET id = uuid;
        """
        with connection.cursor() as cursor:
            cursor.execute(sql)

    elif db_vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute("UPDATE guides_contentguide SET id = uuid;")
            cursor.execute("UPDATE guides_contentguidesection SET id = uuid;")
            cursor.execute("UPDATE guides_contentguidesubsection SET id = uuid;")

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0012_alter_contentguide_id_alter_contentguidesection_id_and_more"),
    ]

    operations = [
        migrations.RunPython(promote_uuid_to_id_guides),
    ]
