# Generated by Django 5.0.13 on 2025-05-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0013_guides_copy_uuid_to_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentguide",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ancestors",
                to="guides.contentguide",
            ),
        ),
        migrations.AlterField(
            model_name="contentguidesection",
            name="content_guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="guides.contentguide",
            ),
        ),
        migrations.AlterField(
            model_name="contentguidesubsection",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsections",
                to="guides.contentguidesection",
            ),
        ),
    ]
