# Generated by Django 5.0.13 on 2025-05-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0014_alter_contentguide_successor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentguide",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentguidesection",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="contentguidesubsection",
            name="uuid",
        ),
    ]
