# Generated by Django 5.2.7 on 2025-10-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0002_initial"),
    ]

    operations = []  # no-op
