# Generated by Django 4.2.7 on 2023-11-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0003_section_html_id_subsection_html_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="coach",
            field=models.CharField(
                blank=True,
                choices=[("july", "July"), ("emily", "Emily"), ("hannah", "Hannah")],
                max_length=16,
            ),
        ),
    ]
