# Generated by Django 4.2.7 on 2023-12-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0010_alter_nofo_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="theme",
            field=models.CharField(
                choices=[
                    ("landscape-cdc-blue", "CDC (Blue)"),
                    ("portrait-hrsa-blue", "HRSA (Blue)"),
                ],
                default="portrait-hrsa-blue",
                help_text="The theme sets the orientation and colour pallete for this NOFO.",
                max_length=32,
            ),
        ),
    ]
