# Generated by Django 4.2.7 on 2023-12-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0011_nofo_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsection",
            name="callout_box",
            field=models.BooleanField(
                default=False,
                help_text="Make this subsection a callout box.",
                verbose_name="Callout box",
            ),
        ),
    ]
