# Generated by Django 4.2.7 on 2023-12-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0012_subsection_callout_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="A short sentence that outlines the high-level goal of this NOFO.",
                max_length=512,
                verbose_name="NOFO tagline",
            ),
        ),
    ]
