# Generated by Django 4.2.9 on 2024-01-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0019_alter_nofo_application_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsection",
            name="tag",
            field=models.CharField(
                choices=[
                    ("h2", "Heading 2"),
                    ("h3", "Heading 3"),
                    ("h4", "Heading 4"),
                    ("h5", "Heading 5"),
                    ("h6", "Heading 6"),
                    ("h7", "Heading 7"),
                ],
                max_length=2,
            ),
        ),
    ]
