# Generated by Django 4.2.9 on 2024-01-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0023_alter_nofo_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="cover",
            field=models.CharField(
                choices=[
                    ("nofo--cover-page--hero", "Hero (large) image"),
                    ("nofo--cover-page--medium", "Medium image"),
                ],
                default="nofo--cover-page--medium",
                help_text="The cover style for the NOFO (eg, large image, medium image, no image).",
                max_length=32,
            ),
        ),
    ]
