# Generated by Django 4.2.9 on 2024-01-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0028_nofo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsection",
            name="is_page_break",
            field=models.BooleanField(
                default=False,
                help_text="If selected, this heading will start on the top of a new page.",
                verbose_name="Has page break?",
            ),
        ),
    ]
