# Generated by Django 4.2.9 on 2024-01-29 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0030_alter_nofo_cover"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsection",
            old_name="is_page_break",
            new_name="has_page_break",
        ),
    ]
