# Generated by Django 4.2.9 on 2024-02-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0034_nofo_author_nofo_keywords_nofo_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="subagency2",
            field=models.CharField(
                blank=True,
                help_text="Another subagency within the agency (eg, Division of Medicine and Dentistry) collaborating on this NOFO",
                max_length=511,
                verbose_name="Subagency 2",
            ),
        ),
    ]
