# Generated by Django 4.2.9 on 2024-02-06 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0037_transfer_has_page_break_to_html_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subsection",
            name="has_page_break",
        ),
    ]
