# Generated by Django 4.2.10 on 2024-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0045_alter_nofo_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="icon_path",
            field=models.CharField(
                blank=True,
                help_text="An override for the icon path if the default doens’t work.",
                max_length=64,
                verbose_name="Icon path",
            ),
        ),
    ]
