# Generated by Django 4.2.10 on 2024-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0046_nofo_icon_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[("adam", "Adam"), ("kevin", "Kevin"), ("emily", "Emily")],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
            ),
        ),
    ]
