# Generated by Django 4.2.10 on 2024-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0047_nofo_designer"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
