# Generated by Django 4.2.10 on 2024-03-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0049_alter_nofo_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="cover",
            field=models.CharField(
                choices=[
                    ("nofo--cover-page--hero", "Hero (large) image"),
                    ("nofo--cover-page--medium", "Small image"),
                    ("nofo--cover-page--text", "No image, large text"),
                ],
                default="nofo--cover-page--medium",
                help_text="The cover style for the NOFO (eg, large image, medium image, no image).",
                max_length=32,
            ),
        ),
    ]
