# Generated by Django 4.2.10 on 2024-03-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0050_alter_nofo_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="icon_style",
            field=models.CharField(
                choices=[
                    ("nofo--icons--border", "White border, transparent background"),
                    ("nofo--icons--solid", "Solid coloured background"),
                ],
                default="nofo--icons--border",
                help_text="Defines the icon style on section cover pages.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="icon_path",
            field=models.CharField(
                blank=True,
                help_text="An override for the icon path if the default doesn’t work.",
                max_length=64,
                verbose_name="Icon path",
            ),
        ),
    ]
