# Generated by Django 4.2.10 on 2024-03-18 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0052_alter_nofo_icon_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nofo",
            name="icon_path",
        ),
    ]
