# Generated by Django 4.2.10 on 2024-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0058_alter_nofo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="inline_css",
            field=models.TextField(
                blank=True,
                help_text="Extra CSS to include for this specific NOFO.",
                verbose_name="Inline CSS",
            ),
        ),
    ]
