# Generated by Django 4.2.10 on 2024-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0059_nofo_inline_css"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="icon_style",
            field=models.CharField(
                choices=[
                    (
                        "nofo--icons--border",
                        "Color background, white icon, white outline (Filled)",
                    ),
                    (
                        "nofo--icons--solid",
                        "White background, color icon, color outline (Standard)",
                    ),
                    (
                        "nofo--icons--thin",
                        "Thin icons with white background, color icon, color outline (Thin)",
                    ),
                ],
                default="nofo--icons--border",
                help_text="Defines the icon style on section cover pages.",
                max_length=32,
            ),
        ),
    ]
