# Generated by Django 4.2.10 on 2024-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0062_alter_nofo_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="The filename used to import this NOFO. If re-imported, this value is the most recent filename.",
                max_length=511,
            ),
        ),
    ]
