# Generated by Django 4.2.14 on 2024-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0067_alter_nofo_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bloom-adam", "Adam"),
                    ("bloom-emily", "Emily"),
                    ("bloom-kevin", "Kevin"),
                    ("bloom-yasmine", "Yasmine"),
                    ("hrsa-betty", "Betty"),
                    ("hrsa-doretha", "Doretha"),
                    ("hrsa-gwen", "Gwen"),
                    ("hrsa-randy", "Randy"),
                    ("hrsa-stephanie", "Stephanie"),
                ],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
            ),
        ),
    ]
