# Generated by Django 5.0.8 on 2024-09-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0069_manually_update_designer_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="archived",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Archived NOFOs are soft-deleted: they are not visible in the UI but can be recovered by superusers.",
                null=True,
            ),
        ),
    ]
