# Generated by Django 5.0.8 on 2024-10-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0070_nofo_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="cover_image",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional URL or path to the cover image.",
                max_length=511,
                verbose_name="Cover image",
            ),
        ),
        migrations.AddField(
            model_name="nofo",
            name="cover_image_alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alternative text for the cover image.",
                max_length=511,
                verbose_name="Cover image alt text",
            ),
        ),
    ]
