# Generated by Django 5.0.8 on 2025-01-10 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0084_populate_section_required_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="agency",
            field=models.CharField(
                blank=True,
                help_text="The agency within the operating division (eg, Bureau of Health Workforce)",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Agency",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="application_deadline",
            field=models.CharField(
                blank=True,
                help_text="The date that applications for this NOFO must be submitted.",
                max_length=200,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Application deadline",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="coach",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aarti", "Aarti"),
                    ("alex", "Alex"),
                    ("emily", "Emily"),
                    ("hannah", "Hannah"),
                    ("idit", "Idit"),
                    ("julie", "Julie"),
                    ("july", "July"),
                    ("mick", "Mick"),
                    ("moira", "Moira"),
                    ("morgan", "Morgan"),
                    ("sara", "Sara"),
                    ("shane", "Shane"),
                ],
                help_text="The coach has the primary responsibility for editing this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="cover",
            field=models.CharField(
                choices=[
                    ("nofo--cover-page--hero", "Full coverage with image"),
                    ("nofo--cover-page--medium", "Standard image"),
                    ("nofo--cover-page--text", "Text only"),
                ],
                default="nofo--cover-page--medium",
                help_text="The cover style for the NOFO.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="cover_image",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional URL or path to the cover image.",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Cover image",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="cover_image_alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alternative text for the cover image.",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Cover image alt text",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bloom-abbey", "Abbey"),
                    ("bloom-adam", "Adam"),
                    ("bloom-emily-b", "Emily\xa0B"),
                    ("bloom-emily-i", "Emily\xa0I"),
                    ("bloom-jackie", "Jackie"),
                    ("bloom-kevin", "Kevin"),
                    ("bloom-yasmine", "Yasmine"),
                    ("hrsa-betty", "Betty"),
                    ("hrsa-doretha", "Doretha"),
                    ("hrsa-gwen", "Gwen"),
                    ("hrsa-ericka", "Ericka"),
                    ("hrsa-jene", "Jene"),
                    ("hrsa-randy", "Randy"),
                    ("hrsa-stephanie", "Stephanie\xa0V"),
                    ("hrsa-kieumy", "KieuMy"),
                ],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="The filename used to import this NOFO. If re-imported, this value is the most recent filename.",
                max_length=511,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(511)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="icon_style",
            field=models.CharField(
                choices=[
                    (
                        "nofo--icons--border",
                        "(Filled) Color background, white icon, white outline",
                    ),
                    (
                        "nofo--icons--solid",
                        "(Outlined) White background, color icon, color outline",
                    ),
                    (
                        "nofo--icons--thin",
                        "(Thin) Thin icons with white background, color icon, color outline",
                    ),
                ],
                default="nofo--icons--border",
                help_text="Defines the icon style on section cover pages.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="The official opportunity number for this NOFO.",
                max_length=200,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Opportunity number",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="opdiv",
            field=models.CharField(
                help_text="The HHS operating division (eg, HRSA, CDC)",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Operating Division",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="A name that makes it easier to find this NOFO in a list. It won’t be public.",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("ready-for-qa", "Ready\xa0for\xa0QA"),
                    ("review", "In\xa0review"),
                    ("published", "Published"),
                ],
                default="draft",
                help_text="The status of this NOFO in the NOFO Builder.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="subagency",
            field=models.CharField(
                blank=True,
                help_text="The subagency within the agency (eg, Division of Medicine and Dentistry)",
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Subagency",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="subagency2",
            field=models.CharField(
                blank=True,
                help_text="Another subagency within the agency (eg, Division of Medicine and Dentistry) collaborating on this NOFO",
                max_length=511,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="Subagency 2",
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="theme",
            field=models.CharField(
                choices=[
                    ("landscape-cdc-blue", "CDC Landscape (Default)"),
                    ("landscape-cdc-white", "CDC Landscape (Light)"),
                    ("portrait-cdc-dop", "CDC Portrait (DOP)"),
                    ("portrait-cdc-orr", "CDC Portrait (ORR)"),
                    ("portrait-cdc-iod", "CDC Portrait (IOD)"),
                    ("portrait-cdc-blue", "CDC Portrait (Default)"),
                    ("portrait-cdc-white", "CDC Portrait (Light)"),
                    ("portrait-acf-white", "ACF (Light)"),
                    ("portrait-acl-white", "ACL (Default)"),
                    ("portrait-aspr-white", "ASPR (Light)"),
                    ("portrait-cms-blue", "CMS (Default)"),
                    ("portrait-cms-white", "CMS (Light)"),
                    ("portrait-hrsa-blue", "HRSA (Default)"),
                    ("portrait-hrsa-white", "HRSA (Light)"),
                    ("portrait-ihs-white", "IHS (Light)"),
                ],
                default="portrait-hrsa-blue",
                help_text="The theme sets the orientation and colour pallete for this NOFO.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="title",
            field=models.TextField(
                blank=True,
                help_text="The official name for this NOFO. It will be public when the NOFO is published.",
                max_length=250,
                validators=[django.core.validators.MaxLengthValidator(250)],
                verbose_name="NOFO title",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="html_id",
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.TextField(max_length=250, verbose_name="Section name"),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="html_class",
            field=models.CharField(
                blank=True,
                max_length=1023,
                validators=[django.core.validators.MaxLengthValidator(1023)],
                verbose_name="HTML class attribute",
            ),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="html_id",
            field=models.CharField(
                blank=True,
                max_length=511,
                validators=[django.core.validators.MaxLengthValidator(511)],
                verbose_name="HTML id attribute",
            ),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="name",
            field=models.TextField(
                blank=True, max_length=400, verbose_name="Subsection name"
            ),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("h2", "Heading 2"),
                    ("h3", "Heading 3"),
                    ("h4", "Heading 4"),
                    ("h5", "Heading 5"),
                    ("h6", "Heading 6"),
                    ("h7", "Heading 7"),
                ],
                max_length=2,
                validators=[django.core.validators.MaxLengthValidator(2)],
            ),
        ),
    ]
