# Generated by Django 5.0.13 on 2025-03-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0092_alter_nofo_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ancestors",
                to="nofos.nofo",
            ),
        ),
    ]
