# Generated by Django 5.0.13 on 2025-04-09 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0095_alter_nofo_coach_alter_nofo_designer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nofo",
            options={"verbose_name": "NOFO", "verbose_name_plural": "NOFOs"},
        ),
        migrations.AlterField(
            model_name="nofo",
            name="archived",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Archived documents are soft-deleted: they are not visible in the UI but can be recovered by superusers.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="The filename used to import this document. If re-imported, this value is the most recent filename.",
                max_length=511,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(511)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="group",
            field=models.CharField(
                choices=[
                    ("bloom", "Bloomworks"),
                    ("acf", "ACF: Administration for Children and Families"),
                    ("acl", "ACL: Administration for Community Living"),
                    (
                        "aspr",
                        "ASPR: Administration for Strategic Preparedness and Response",
                    ),
                    ("cdc", "CDC: Centers for Disease Control and Prevention"),
                    ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                    ("hrsa", "HRSA: Health Resources and Services Administration"),
                    ("ihs", "IHS: Indian Health Service"),
                    ("staging", "Staging environment"),
                ],
                default="bloom",
                help_text="The OpDiv grouping for this document. The group is used to control access to a NOFO. The 'Bloomworks' group can be used to hide NOFOs from OpDiv users.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("ready-for-qa", "Ready\xa0for\xa0QA"),
                    ("review", "In\xa0review"),
                    ("published", "Published"),
                    ("paused", "Paused"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                help_text="The status of this document in the NOFO Builder.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
    ]
