# Generated by Django 5.0.13 on 2025-04-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0096_alter_nofo_options_alter_nofo_archived_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="subsection",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="subsection",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nofo_subsections",
                to="nofos.section",
            ),
        ),
    ]
