# Generated by Django 5.0.13 on 2025-04-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0097_alter_section_options_alter_subsection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsection",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsections",
                to="nofos.section",
            ),
        ),
    ]
