# Generated by Django 5.0.13 on 2025-05-05 19:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0098_alter_subsection_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="subsection",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
