# Generated by Django 5.0.13 on 2025-05-07 20:30

from django.db import connection, migrations


def update_foreign_keys_to_uuid_nofos(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        with connection.cursor() as cursor:
            # NOFO Successor
            cursor.execute("""
                UPDATE nofos_nofo AS n1
                SET successor = n2.uuid::text
                FROM nofos_nofo n2
                WHERE n1.successor IS NOT NULL AND n1.successor::text = n2.id::text;
                """)

            # Section NOFO Foreign Key
            cursor.execute("""
                UPDATE nofos_section AS s
                SET nofo = n.uuid::text
                FROM nofos_nofo n
                WHERE s.nofo::text = n.id::text;
                """)

            # Subsection Section Foreign Key
            cursor.execute("""
                UPDATE nofos_subsection AS ss
                SET section = s.uuid::text
                FROM nofos_section s
                WHERE ss.section::text = s.id::text;
                """)

    elif db_vendor == "sqlite":
        with connection.cursor() as cursor:
            # Temporarily disable foreign key checks
            cursor.execute("PRAGMA foreign_keys=OFF;")

            # Split the SQLite queries into separate commands
            cursor.execute("""
                UPDATE nofos_nofo 
                SET successor = (
                    SELECT n2.uuid 
                    FROM nofos_nofo n2 
                    WHERE n2.id = nofos_nofo.successor
                )
                WHERE successor IS NOT NULL;
            """)
            cursor.execute("""
                UPDATE nofos_section 
                SET nofo = (SELECT uuid FROM nofos_nofo WHERE id = nofo);
            """)
            cursor.execute("""
                UPDATE nofos_subsection 
                SET section = (SELECT uuid FROM nofos_section WHERE id = section);
            """)

            # Re-enable foreign key checks
            cursor.execute("PRAGMA foreign_keys=ON;")

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0102_alter_nofo_successor_alter_section_nofo_and_more"),
    ]

    operations = [
        migrations.RunPython(update_foreign_keys_to_uuid_nofos),
    ]
