# Generated by Django 5.0.13 on 2025-05-07 22:05
from django.db import connection, migrations


def update_easyaudit_nofos_to_uuid(apps, schema_editor):
    db_vendor = connection.vendor

    if db_vendor == "postgresql":
        sql = """
            -- PostgreSQL: Update NOFO IDs in EasyAudit to UUIDs with quoted UUIDs in JSON
            UPDATE easyaudit_crudevent
            SET object_id = n.uuid::text,
                object_json_repr = REGEXP_REPLACE(object_json_repr, '"pk": \\d+', '"pk": "' || n.uuid || '"', 'g')
            FROM nofos_nofo n
            WHERE easyaudit_crudevent.object_json_repr LIKE '%"model": "nofos.nofo"%'
            AND CAST(easyaudit_crudevent.object_id AS INTEGER) = n.id;

            -- Sections
            UPDATE easyaudit_crudevent
            SET object_id = s.uuid::text,
                object_json_repr = REGEXP_REPLACE(object_json_repr, '"pk": \\d+', '"pk": "' || s.uuid || '"', 'g')
            FROM nofos_section s
            WHERE easyaudit_crudevent.object_json_repr LIKE '%"model": "nofos.section"%'
            AND CAST(easyaudit_crudevent.object_id AS INTEGER) = s.id;

            -- Subsections
            UPDATE easyaudit_crudevent
            SET object_id = ss.uuid::text,
                object_json_repr = REGEXP_REPLACE(object_json_repr, '"pk": \\d+', '"pk": "' || ss.uuid || '"', 'g')
            FROM nofos_subsection ss
            WHERE easyaudit_crudevent.object_json_repr LIKE '%"model": "nofos.subsection"%'
            AND CAST(easyaudit_crudevent.object_id AS INTEGER) = ss.id;
        """
        with connection.cursor() as cursor:
            cursor.execute(sql)

    elif db_vendor == "sqlite":
        with connection.cursor() as cursor:
            # NOFOs
            cursor.execute("""
                UPDATE easyaudit_crudevent
                SET object_id = (
                    SELECT
                        SUBSTR(uuid, 1, 8) || '-' ||
                        SUBSTR(uuid, 9, 4) || '-' ||
                        SUBSTR(uuid, 13, 4) || '-' ||
                        SUBSTR(uuid, 17, 4) || '-' ||
                        SUBSTR(uuid, 21)
                    FROM nofos_nofo WHERE CAST(object_id AS INTEGER) = id
                ),
                object_json_repr = REPLACE(
                    object_json_repr,
                    '"pk": ' || object_id,
                    '"pk": "' ||
                    SUBSTR((SELECT uuid FROM nofos_nofo WHERE CAST(object_id AS INTEGER) = id), 1, 8) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_nofo WHERE CAST(object_id AS INTEGER) = id), 9, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_nofo WHERE CAST(object_id AS INTEGER) = id), 13, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_nofo WHERE CAST(object_id AS INTEGER) = id), 17, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_nofo WHERE CAST(object_id AS INTEGER) = id), 21)
                    || '"'
                )
                WHERE object_json_repr LIKE '%"model": "nofos.nofo"%';
                """)

            # Sections
            cursor.execute("""
                UPDATE easyaudit_crudevent
                SET object_id = (
                    SELECT
                        SUBSTR(uuid, 1, 8) || '-' ||
                        SUBSTR(uuid, 9, 4) || '-' ||
                        SUBSTR(uuid, 13, 4) || '-' ||
                        SUBSTR(uuid, 17, 4) || '-' ||
                        SUBSTR(uuid, 21)
                    FROM nofos_section WHERE CAST(object_id AS INTEGER) = id
                ),
                object_json_repr = REPLACE(
                    object_json_repr,
                    '"pk": ' || object_id,
                    '"pk": "' ||
                    SUBSTR((SELECT uuid FROM nofos_section WHERE CAST(object_id AS INTEGER) = id), 1, 8) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_section WHERE CAST(object_id AS INTEGER) = id), 9, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_section WHERE CAST(object_id AS INTEGER) = id), 13, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_section WHERE CAST(object_id AS INTEGER) = id), 17, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_section WHERE CAST(object_id AS INTEGER) = id), 21)
                    || '"'
                )
                WHERE object_json_repr LIKE '%"model": "nofos.section"%';
                """)

            # Subsections
            cursor.execute("""
                UPDATE easyaudit_crudevent
                SET object_id = (
                    SELECT
                        SUBSTR(uuid, 1, 8) || '-' ||
                        SUBSTR(uuid, 9, 4) || '-' ||
                        SUBSTR(uuid, 13, 4) || '-' ||
                        SUBSTR(uuid, 17, 4) || '-' ||
                        SUBSTR(uuid, 21)
                    FROM nofos_subsection WHERE CAST(object_id AS INTEGER) = id
                ),
                object_json_repr = REPLACE(
                    object_json_repr,
                    '"pk": ' || object_id,
                    '"pk": "' ||
                    SUBSTR((SELECT uuid FROM nofos_subsection WHERE CAST(object_id AS INTEGER) = id), 1, 8) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_subsection WHERE CAST(object_id AS INTEGER) = id), 9, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_subsection WHERE CAST(object_id AS INTEGER) = id), 13, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_subsection WHERE CAST(object_id AS INTEGER) = id), 17, 4) || '-' ||
                    SUBSTR((SELECT uuid FROM nofos_subsection WHERE CAST(object_id AS INTEGER) = id), 21)
                    || '"'
                )
                WHERE object_json_repr LIKE '%"model": "nofos.subsection"%';
                """)

    else:
        raise RuntimeError("Unsupported database type: " + db_vendor)


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0104_nofos_clean_easyaudit_records_for_deleted_objects"),
    ]

    operations = [
        migrations.RunPython(update_easyaudit_nofos_to_uuid),
    ]
