# Generated by Django 5.0.13 on 2025-05-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0108_alter_nofo_successor_alter_section_nofo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nofo",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="section",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="subsection",
            name="uuid",
        ),
    ]
