# Generated by Django 5.2.3 on 2025-06-19 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0109_remove_nofo_uuid_remove_section_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsection",
            name="name",
            field=models.TextField(
                blank=True,
                max_length=400,
                validators=[django.core.validators.MaxLengthValidator(400)],
                verbose_name="Subsection name",
            ),
        ),
    ]
