# Generated by Django 5.2.3 on 2025-06-25 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0111_alter_nofo_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("ready-for-qa", "Ready\xa0for\xa0QA"),
                    ("review", "In\xa0review"),
                    ("doge", "DOGE"),
                    ("published", "Published"),
                    ("paused", "Paused"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                help_text="The status of this document in the NOFO Builder.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
    ]
