# Generated by Django 5.2.3 on 2025-07-23 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0114_add_html_class_to_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="html_class",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1023,
                validators=[django.core.validators.MaxLengthValidator(1023)],
                verbose_name="HTML class attribute",
            ),
        ),
        migrations.AlterField(
            model_name="subsection",
            name="html_class",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1023,
                validators=[django.core.validators.MaxLengthValidator(1023)],
                verbose_name="HTML class attribute",
            ),
        ),
    ]
