# Generated by Django 5.2.6 on 2025-09-16 17:03

from django.db import migrations, models


def migrate_before_you_begin(apps, schema_editor):
    Nofo = apps.get_model("nofos", "Nofo")
    for nofo in Nofo.objects.all():
        if nofo.sole_source_justification:
            nofo.before_you_begin = "sole_source"
        else:
            nofo.before_you_begin = "full"
        nofo.save(update_fields=["before_you_begin"])


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0116_alter_nofo_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="before_you_begin",
            field=models.CharField(
                choices=[
                    ("full", "Full BYB page"),
                    ("sole_source", "Sole Source Justification"),
                    ("none", "No BYB page"),
                ],
                default="full",
                help_text="Controls how the 'Before you begin' page is presented. Choices are 'Full', 'Sole Source' (for 1 applicant), and 'None'.",
                max_length=20,
                verbose_name="Before You Begin page",
            ),
        ),
        migrations.RunPython(migrate_before_you_begin, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="nofo",
            name="sole_source_justification",
        ),
    ]
