# Generated by Django 5.2.6 on 2025-09-30 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0117_remove_nofo_sole_source_justification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bloom-abbey", "Abbey"),
                    ("bloom-adam", "Adam"),
                    ("bloom-emily-b", "Emily\xa0B"),
                    ("bloom-emily-i", "Emily\xa0I"),
                    ("bloom-jackie", "Jackie"),
                    ("bloom-jana", "Jana"),
                    ("bloom-kevin", "Kevin"),
                    ("bloom-yasmine", "Yasmine"),
                    ("hrsa-betty", "Betty"),
                    ("hrsa-dvora", "Dvora"),
                    ("hrsa-ericka", "Ericka"),
                    ("hrsa-jene", "Jene"),
                    ("hrsa-jennifer", "Jennifer"),
                    ("hrsa-kerry", "Kerry"),
                    ("hrsa-kieumy", "KieuMy"),
                    ("hrsa-lynda", "Lynda"),
                    ("hrsa-marco", "Marco"),
                    ("hrsa-randy", "Randy"),
                    ("hrsa-stephanie", "Stephanie\xa0V"),
                ],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
    ]
