# Generated by Django 5.2.7 on 2025-10-28 00:01
from django.db import migrations


def forwards(apps, schema_editor):
    Nofo = apps.get_model("nofos", "Nofo")
    qs = Nofo._base_manager  # <-- bypass default manager filters

    retired_coaches = ["aarti", "alex", "emily", "hannah", "july"]
    retired_designers = [
        "bloom-abbey",
        "bloom-emily-b",
        "bloom-emily-i",
        "bloom-jackie",
        "bloom-kevin",
    ]

    qs.filter(coach__in=retired_coaches).update(coach="")
    qs.filter(designer__in=retired_designers).update(designer="")


class Migration(migrations.Migration):
    dependencies = [
        ("nofos", "0121_alter_nofo_coach_alter_nofo_designer"),
    ]
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]


def backwards(apps, schema_editor):
    # No safe reversal (we don't know which values to restore)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0119_nofo_updated_by"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
