# Generated by Django 5.2.7 on 2025-10-28 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0120_clear_retired_coaches_designers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="coach",
            field=models.CharField(
                blank=True,
                choices=[
                    ("laura", "Laura\xa0W"),
                    ("julie", "Julie\xa0H"),
                    ("moira", "Moira"),
                    ("sara_d", "Sara\xa0D"),
                    ("sara_t", "Sara\xa0T"),
                ],
                help_text="The coach has the primary responsibility for editing this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bloom-adam", "Adam"),
                    ("bloom-ben-b", "Ben\xa0B"),
                    ("bloom-jana", "Jana"),
                    ("bloom-yasmine", "Yasmine"),
                    ("hrsa-betty", "Betty"),
                    ("hrsa-dvora", "Dvora"),
                    ("hrsa-ericka", "Ericka"),
                    ("hrsa-jene", "Jene"),
                    ("hrsa-jennifer", "Jennifer"),
                    ("hrsa-kerry", "Kerry"),
                    ("hrsa-kieumy", "KieuMy"),
                    ("hrsa-lynda", "Lynda"),
                    ("hrsa-marco", "Marco"),
                    ("hrsa-randy", "Randy"),
                    ("hrsa-stephanie", "Stephanie\xa0V"),
                ],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
    ]
