# Generated by Django 5.2.9 on 2026-01-06 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0121_alter_nofo_coach_alter_nofo_designer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="theme",
            field=models.CharField(
                choices=[
                    ("landscape-cdc-blue", "CDC Landscape (Default)"),
                    ("landscape-cdc-white", "CDC Landscape (Light)"),
                    ("portrait-cdc-ncipc1", "CDC Portrait (NCIPC Blue)"),
                    ("portrait-cdc-ncipc2", "CDC Portrait (NCIPC Teal)"),
                    ("portrait-cdc-dghp", "CDC Portrait (DGHP)"),
                    ("portrait-cdc-dhp", "CDC Portrait (DHP)"),
                    ("portrait-cdc-iod", "CDC Portrait (IOD)"),
                    ("portrait-cdc-orr", "CDC Portrait (ORR)"),
                    ("portrait-cdc-blue", "CDC Portrait (Default)"),
                    ("portrait-cdc-white", "CDC Portrait (Light)"),
                    ("portrait-acf-white", "ACF (Light)"),
                    ("portrait-acl-white", "ACL (Default)"),
                    ("portrait-aspr-white", "ASPR (Light)"),
                    ("portrait-cms-blue", "CMS (Default)"),
                    ("portrait-cms-white", "CMS (Light)"),
                    ("portrait-hrsa-blue", "HRSA (Default)"),
                    ("portrait-hrsa-white", "HRSA (Light)"),
                    ("portrait-ihs-white", "IHS (Light)"),
                    ("portrait-samhsa-white", "SAMHSA (Light)"),
                ],
                default="portrait-hrsa-blue",
                help_text="The theme sets the orientation and colour pallete for this NOFO.",
                max_length=32,
                validators=[django.core.validators.MaxLengthValidator(32)],
            ),
        ),
    ]
