# Generated by Django 6.0.3 on 2026-03-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0123_alter_nofo_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="before_you_begin",
            field=models.CharField(
                choices=[
                    ("full", "Full BYB page"),
                    ("era", "BYB page with eRA"),
                    ("sole_source", "Sole Source Justification"),
                    ("none", "No BYB page"),
                ],
                default="full",
                help_text="Controls how the 'Before you begin' page is presented. Choices are 'Full', 'BYB page with eRA', 'Sole Source' (for 1 applicant), and 'None'.",
                max_length=20,
                verbose_name="Before You Begin page",
            ),
        ),
    ]
