# Generated by Django 6.0.3 on 2026-03-17 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0124_alter_nofo_before_you_begin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="coach",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ashley", "Ashley"),
                    ("jennifer", "Jennifer"),
                    ("julie", "Julie\xa0H"),
                    ("laura", "Laura\xa0W"),
                    ("moira", "Moira"),
                    ("sara_d", "Sara\xa0D"),
                    ("sara_t", "Sara\xa0T"),
                ],
                help_text="The coach has the primary responsibility for editing this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
    ]
