# Generated by Django 6.0.4 on 2026-04-15 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0125_alter_nofo_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bloom-adam", "Adam"),
                    ("bloom-andrea-c", "Andrea\xa0C"),
                    ("bloom-ben-b", "Ben\xa0B"),
                    ("bloom-jana", "Jana"),
                    ("bloom-yasmine", "Yasmine"),
                    ("hrsa-betty", "Betty"),
                    ("hrsa-dvora", "Dvora"),
                    ("hrsa-ericka", "Ericka"),
                    ("hrsa-jene", "Jene"),
                    ("hrsa-jennifer", "Jennifer"),
                    ("hrsa-kerry", "Kerry"),
                    ("hrsa-kieumy", "KieuMy"),
                    ("hrsa-lynda", "Lynda"),
                    ("hrsa-marco", "Marco"),
                    ("hrsa-randy", "Randy"),
                    ("hrsa-stephanie", "Stephanie\xa0V"),
                ],
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=16,
                validators=[django.core.validators.MaxLengthValidator(16)],
            ),
        ),
    ]
