# Generated by Django 6.0.3 on 2026-06-08 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0127_alter_nofo_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nofo",
            name="designer",
            field=models.CharField(
                blank=True,
                help_text="The designer is responsible for the layout of this NOFO.",
                max_length=200,
                validators=[django.core.validators.MaxLengthValidator(200)],
            ),
        ),
    ]
