# Generated by Django 6.0.7 on 2026-08-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0129_alter_nofo_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsection",
            name="policy_language_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Not policy language"),
                    ("intact", "Matches current canonical text"),
                    ("matches_prior_version", "Matches a prior canonical version"),
                    ("may_be_altered", "May be altered"),
                ],
                default="none",
                help_text="Set at import time by diffing this subsection against the canonical HHS policy-language store. Deliberately excludes a 'missing' state: a required PolicyLanguageSlot with no matching subsection anywhere in the NOFO is a fact about the NOFO as a whole, not about any single subsection, and is checked separately rather than stored here.",
                max_length=32,
                verbose_name="Policy language status",
            ),
        ),
        migrations.CreateModel(
            name="PolicyLanguageSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_key",
                    models.CharField(
                        help_text="Human-readable reference id, e.g. 'DG-017'.",
                        max_length=32,
                        unique=True,
                        verbose_name="Slot key",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Slot name")),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("fixed_with_placeholders", "Fixed with placeholders"),
                            ("one_of_n_options", "One of N options"),
                            ("parameterized_family", "Parameterized family"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "match_scope",
                    models.CharField(
                        choices=[
                            ("whole_subsection", "Whole subsection"),
                            ("span_within_subsection", "Span within subsection"),
                        ],
                        default="whole_subsection",
                        max_length=32,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this slot's total absence from a NOFO is itself flagged (checked at the Nofo level, not stored per-subsection).",
                    ),
                ),
                (
                    "flag_prominently",
                    models.BooleanField(
                        default=False,
                        help_text="If true, a non-intact status for this slot gets elevated wording at export instead of the routine flag. Reserved for a small, deliberately curated set of slots — set explicitly here, never inferred.",
                        verbose_name="Flag prominently",
                    ),
                ),
                (
                    "template_version",
                    models.CharField(
                        blank=True,
                        help_text="Which canonical source version this slot came from, e.g. 'FY27-draft-2026-08-11'.",
                        max_length=64,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="False once superseded by a newer canonical revision.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="nofos.policylanguageslot",
                    ),
                ),
            ],
            options={
                "ordering": ["slot_key"],
            },
        ),
        migrations.AddField(
            model_name="subsection",
            name="policy_language_slot",
            field=models.ForeignKey(
                blank=True,
                help_text="The canonical slot this subsection was aligned to, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_subsections",
                to="nofos.policylanguageslot",
            ),
        ),
        migrations.CreateModel(
            name="PolicyLanguageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Option 1: Grants.gov', or '15%' for a parameterized family.",
                        max_length=255,
                        verbose_name="Variant label",
                    ),
                ),
                (
                    "parameter_value",
                    models.CharField(
                        blank=True,
                        help_text="For 'parameterized_family' slots: the extracted parameter this variant corresponds to, e.g. '15'.",
                        max_length=64,
                        verbose_name="Parameter value",
                    ),
                ),
                (
                    "canonical_text",
                    models.TextField(
                        help_text="Verbatim canonical text. Placeholder spans use the source template's own {Insert...} bracket convention.",
                        verbose_name="Canonical text",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="nofos.policylanguageslot",
                    ),
                ),
            ],
            options={
                "ordering": ["slot", "id"],
            },
        ),
    ]
