# Generated by Django 6.0.7 on 2026-08-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0130_subsection_policy_language_status_policylanguageslot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policylanguageslot",
            name="slot_key",
            field=models.CharField(
                help_text="Human-readable reference id, e.g. 'DG-017'. Not unique across all rows on purpose: superseded (is_current=False) revisions keep the same slot_key as the current one, per the versioning design. Only one row per slot_key may be is_current=True at a time (enforced below).",
                max_length=32,
                verbose_name="Slot key",
            ),
        ),
        migrations.AddConstraint(
            model_name="policylanguageslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("slot_key",),
                name="unique_current_policy_language_slot_key",
            ),
        ),
    ]
