# Generated by Django 6.0.7 on 2026-08-25 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0131_alter_policylanguageslot_slot_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NofoReadabilityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nofo_revision",
                    models.DateTimeField(
                        help_text="Nofo.updated at the moment of calculation: the content revision these metrics describe, and the same value passed to the package as 'revision'. A snapshot is current while this matches Nofo.updated."
                    ),
                ),
                (
                    "profile_reference",
                    models.CharField(
                        help_text="Metrics profile used, eg 'hhs-nofo-fy27-html@0.4.0'.",
                        max_length=128,
                    ),
                ),
                (
                    "package_version",
                    models.CharField(
                        help_text="Installed hhs-nofo-metrics version, eg '0.5.2'.",
                        max_length=32,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        blank=True,
                        help_text="result['schema_version'] from the payload, eg '1.1.0'. This is the result contract version, which moves independently of the package version and the profile.",
                        max_length=32,
                    ),
                ),
                (
                    "result_basis",
                    models.CharField(
                        blank=True,
                        help_text="result['result_basis'] from the payload, eg 'structured_estimate'.",
                        max_length=64,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="True when every metric the package returned had status 'calculated'. The package reports a status per metric, so a successful analysis can still carry unavailable measurements. Those snapshots are kept, but never stand in for the latest successful measurement. Judged against the metrics actually returned, not against GOAL_METRIC_IDS, which is the separate set Builder allows goals to be configured for.",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        help_text="The package's complete AnalysisResult payload, stored unflattened: schema_version, result_basis, source, coverage, metrics, and notes. Metric values are not flattened into columns, so the stored snapshot keeps the package's own contract."
                    ),
                ),
                (
                    "goals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Normalized HHS_NOFO_METRIC_GOALS in effect when this was calculated, recorded so a snapshot can be interpreted later. Live comparisons in the panel render from current configuration, not from this copy.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who ran the calculation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nofo",
                    models.ForeignKey(
                        help_text="Deleting a NOFO deletes its readability history, matching the existing behavior for succeeded NOFOs. Archiving a NOFO is a soft delete and leaves its snapshots intact.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readability_scores",
                        to="nofos.nofo",
                    ),
                ),
            ],
            options={
                "verbose_name": "NOFO readability score",
                "verbose_name_plural": "NOFO readability scores",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_complete", True)),
                        fields=["nofo", "-created_at"],
                        name="readability_latest_ok_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "nofo",
                            "nofo_revision",
                            "profile_reference",
                            "package_version",
                        ),
                        name="unique_readability_score_per_nofo_revision",
                    )
                ],
            },
        ),
    ]
