# Generated by Django 6.0.8 on 2026-09-03 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0132_noforeadabilityscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="nofo",
            name="assistance_listing_number",
            field=models.CharField(
                blank=True,
                help_text="The CFDA number for this NOFO, as it appears in SAM.gov (eg, 93.884).",
                max_length=6,
                validators=[django.core.validators.MaxLengthValidator(6)],
                verbose_name="Assistance listing number",
            ),
        ),
    ]
