# Generated by Django 6.0.8 on 2026-09-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0133_nofo_assistance_listing_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="The uploaded file's name, as submitted.",
                        max_length=255,
                    ),
                ),
                (
                    "is_reimport",
                    models.BooleanField(
                        default=False,
                        help_text="True if this was a reimport (overwrite) of an existing NOFO, rather than a new NOFO import.",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="The blocking error code shown to the user (eg 'IMPORT-OPDIV-BLANK'), or blank if the import succeeded.",
                        max_length=64,
                    ),
                ),
                (
                    "warning_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of non-blocking Word-formatting warnings mammoth reported for this attempt. Always 0 for HTML-file uploads, which never go through mammoth.",
                    ),
                ),
                (
                    "nofo",
                    models.ForeignKey(
                        blank=True,
                        help_text="The NOFO this attempt created or overwrote, if it succeeded. Null for failed new-NOFO imports, since no NOFO exists to point to. If the NOFO is later deleted, this row is kept with nofo set to null, so the historical count of attempts doesn't change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_attempts",
                        to="nofos.nofo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who attempted the import.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import attempt",
                "verbose_name_plural": "Import attempts",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
