# Generated by Django 6.0.8 on 2026-09-05 00:00

from django.db import migrations


def create_metrics_viewers_group(apps, schema_editor):
    """Ensure a "Metrics viewers" group exists and carries the new permission."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    nofo_content_type = ContentType.objects.get(app_label="nofos", model="nofo")
    permission, _ = Permission.objects.get_or_create(
        codename="view_builder_metrics",
        content_type=nofo_content_type,
        defaults={"name": "Can view NOFO Builder usage & quality metrics"},
    )

    group, _ = Group.objects.get_or_create(name="Metrics viewers")
    group.permissions.add(permission)


def remove_metrics_viewers_group(apps, schema_editor):
    """Reverse migration: drop the group. Leaves the permission row itself
    (reversing the preceding AlterModelOptions is what actually removes it)."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Metrics viewers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0134_importattempt"),
        ("auth", "0001_initial"),
        ("contenttypes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nofo",
            options={
                "verbose_name": "NOFO",
                "verbose_name_plural": "NOFOs",
                "permissions": [
                    (
                        "view_builder_metrics",
                        "Can view NOFO Builder usage & quality metrics",
                    )
                ],
            },
        ),
        migrations.RunPython(
            create_metrics_viewers_group, remove_metrics_viewers_group
        ),
    ]
