# Generated by Django 6.0.7 on 2026-09-08 14:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0135_nofo_view_builder_metrics_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsNofo",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                ("included", models.BooleanField()),
                ("first_live_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="importattempt",
            name="metrics_included",
            field=models.BooleanField(
                editable=False,
                help_text="Eligibility at import time; null means historical attribution is unknown.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MetricsActor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(db_index=True)),
                ("included", models.BooleanField()),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetricsActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nofos.metricsactor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "month"), name="metrics_actor_month"
                    )
                ],
            },
        ),
    ]
