# Generated by Django 6.0.7 on 2026-09-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0137_metrics_history_baseline"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="metricsactivity",
            name="metrics_actor_month",
        ),
        migrations.AddField(
            model_name="importattempt",
            name="metrics_group",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="metricsactivity",
            name="group",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="metricsactor",
            name="group",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="metricsnofo",
            name="group",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=16
            ),
        ),
        migrations.AddConstraint(
            model_name="metricsactivity",
            constraint=models.UniqueConstraint(
                fields=("actor", "month", "group"), name="metrics_actor_month_group"
            ),
        ),
    ]
