# Generated by Django 6.0.8 on 2026-09-16 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0140_hrsa_before_you_begin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="importattempt",
            index=models.Index(
                fields=["created_at"], name="import_attempt_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importattempt",
            index=models.Index(
                fields=["error_code", "created_at"], name="import_attempt_error_idx"
            ),
        ),
    ]
