# Generated by Django 6.0.6 on 2026-09-17 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0141_import_attempt_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="noforeadabilityscore",
            name="unique_readability_score_per_nofo_revision",
        ),
        migrations.AddField(
            model_name="noforeadabilityscore",
            name="input_contract_version",
            field=models.CharField(
                default="word-export-v1",
                help_text="Builder metrics rendering contract. word-export-v1 includes PDF metadata; word-export-v2 excludes it. Legacy snapshots retain v1.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="noforeadabilityscore",
            constraint=models.UniqueConstraint(
                fields=(
                    "nofo",
                    "nofo_revision",
                    "profile_reference",
                    "package_version",
                    "input_contract_version",
                ),
                name="unique_readability_score_per_nofo_revision",
            ),
        ),
    ]
