# Generated by Django 6.0.8 on 2026-09-23 17:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0142_readability_input_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSourceHandoff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_system", models.CharField(max_length=128)),
                ("source_record_id", models.CharField(max_length=255)),
                ("source_version", models.CharField(max_length=255)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("bloom", "Bloomworks"),
                            ("acf", "ACF: Administration for Children and Families"),
                            ("acl", "ACL: Administration for Community Living"),
                            (
                                "aspr",
                                "ASPR: Administration for Strategic Preparedness and Response",
                            ),
                            ("cdc", "CDC: Centers for Disease Control and Prevention"),
                            ("cms", "CMS: Centers for Medicare & Medicaid Services"),
                            (
                                "hrsa",
                                "HRSA: Health Resources and Services Administration",
                            ),
                            ("ihs", "IHS: Indian Health Service"),
                            ("nih", "NIH: National Institutes of Health"),
                            ("staging", "Staging environment"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("state", models.CharField(default="received", max_length=32)),
                (
                    "state_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "nofo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_source_handoffs",
                        to="nofos.nofo",
                    ),
                ),
                (
                    "linked_nofo_uuid",
                    models.UUIDField(
                        blank=True,
                        editable=False,
                        help_text="Stable linkage tombstone if the Builder NOFO is later deleted.",
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_system", "source_record_id", "source_version"),
                        name="unique_external_source_handoff_version",
                    )
                ],
            },
        ),
    ]
