# Generated by Django 6.0.8 on 2026-09-29 11:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def preserve_existing_links(apps, schema_editor):
    Receipt = apps.get_model("nofos", "ExternalSourceHandoff")
    Result = apps.get_model("nofos", "ExternalSourceHandoffResult")
    Current = apps.get_model("nofos", "ExternalSourceHandoffCurrent")
    for receipt in (
        Receipt.objects.using(schema_editor.connection.alias).all().iterator()
    ):
        linked_uuid = receipt.linked_nofo_uuid
        live_uuid = receipt.nofo_id
        if live_uuid is not None and linked_uuid != live_uuid:
            raise ValueError(
                f"Malformed legacy handoff link for receipt {receipt.pk}: live NOFO and tombstone differ"
            )
        if linked_uuid is None:
            continue
        result = Result.objects.using(schema_editor.connection.alias).create(
            handoff_id=receipt.pk,
            nofo_id=live_uuid,
            linked_nofo_uuid=linked_uuid,
            created_at=receipt.received_at,
        )
        Current.objects.using(schema_editor.connection.alias).create(
            handoff_id=receipt.pk, result_id=result.pk
        )


def reverse_only_if_empty(apps, schema_editor):
    Result = apps.get_model("nofos", "ExternalSourceHandoffResult")
    Current = apps.get_model("nofos", "ExternalSourceHandoffCurrent")
    alias = schema_editor.connection.alias
    if Result.objects.using(alias).exists() or Current.objects.using(alias).exists():
        raise IrreversibleError(
            "Handoff result history cannot be reversed without losing identity"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0143_externalsourcehandoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSourceHandoffResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "linked_nofo_uuid",
                    models.UUIDField(
                        editable=False,
                        help_text="Stable linkage tombstone if the Builder NOFO is later deleted.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "reviewer_id",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "authorization_reference",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "decision_id",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "handoff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="nofos.externalsourcehandoff",
                    ),
                ),
                (
                    "nofo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_source_handoff_results",
                        to="nofos.nofo",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement",
                        to="nofos.externalsourcehandoffresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalSourceHandoffCurrent",
            fields=[
                (
                    "handoff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="current_selection",
                        serialize=False,
                        to="nofos.externalsourcehandoff",
                    ),
                ),
                (
                    "result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_selection",
                        to="nofos.externalsourcehandoffresult",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="externalsourcehandoffresult",
            constraint=models.UniqueConstraint(
                fields=("handoff", "linked_nofo_uuid"),
                name="unique_external_handoff_nofo_uuid",
            ),
        ),
        migrations.RunPython(preserve_existing_links, reverse_only_if_empty),
        migrations.RemoveField(
            model_name="externalsourcehandoff",
            name="linked_nofo_uuid",
        ),
        migrations.RemoveField(
            model_name="externalsourcehandoff",
            name="nofo",
        ),
    ]
