# Generated by Django 6.0.6 on 2026-09-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0144_remove_externalsourcehandoff_linked_nofo_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfReadabilityAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("outcome", models.CharField(max_length=32)),
                ("http_status", models.PositiveSmallIntegerField()),
                ("duration_ms", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
