# Generated by Django 6.0.8 on 2026-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0147_noforeadabilitycheckpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="noforeadabilitycheckpoint",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Saved by a user"),
                    ("import", "Saved automatically on import"),
                    ("reimport", "Saved automatically on re-import"),
                ],
                default="manual",
                help_text="What created this checkpoint. Imports and re-imports save one automatically so every NOFO has a starting point to compare against.",
                max_length=16,
            ),
        ),
    ]
