# Generated by Django 6.0.8 on 2026-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nofos", "0148_readability_checkpoint_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noforeadabilitycheckpoint",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Saved by a user"),
                    ("import", "Saved automatically on import"),
                    ("reimport", "Saved automatically on re-import"),
                    ("download", "Saved automatically on PDF download"),
                ],
                default="manual",
                help_text="What created this checkpoint. Imports, re-imports and finished PDF downloads save one automatically when the NOFO has changed, so every NOFO has a starting point and a record of what was produced.",
                max_length=16,
            ),
        ),
    ]
