# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
name: "Build Django Docker container and deploy to Cloud Run"

on:
  workflow_call: # Allow this workflow to be called by other workflows
    inputs:
      github_sha:
        description: "Github SHA of current commit: used to tag the image"
        required: true
        type: "string"
    secrets:
      GCP_AR_REPO_NAME:
        required: true
      GCP_IAM_SA_CREDENTIALS:
        required: true
      GCP_PROJECT_ID:
        required: true
      GCP_SERVICE_NAME:
        required: true

env:
  AR_REGION: "us"
  SERVICE_REGION: "us-central1"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      # Configure auth with Service Account with permissions to build and deploy on Google Cloud
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_IAM_SA_CREDENTIALS }}

      # BEGIN - Docker auth and build
      - name: "Docker Auth"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ env.AR_REGION }}-docker.pkg.dev"
          username: _json_key
          password: ${{ secrets.GCP_IAM_SA_CREDENTIALS }}

      - name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_AR_REPO_NAME }}/${{ secrets.GCP_SERVICE_NAME }}:${{ inputs.github_sha }}"
          echo $DOCKER_TAG
          docker build --no-cache --tag "${DOCKER_TAG}" --build-arg IS_PROD_ARG=1 --build-arg GITHUB_SHA_ARG="${{ inputs.github_sha }}" .
          docker push "${DOCKER_TAG}"
        # END - Docker auth and build

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ secrets.GCP_SERVICE_NAME }}"
          region: "${{ env.SERVICE_REGION }}"
          image: "${{ env.AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_AR_REPO_NAME }}/${{ secrets.GCP_SERVICE_NAME }}:${{ inputs.github_sha }}"
