# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.

name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - main-1

env:
  AR_REGION: "us"
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY: ${{ secrets.GCP_AR_REPO_NAME }}
  SERVICE: ${{ secrets.GCP_SERVICE_NAME }}
  SERVICE_REGION: "us-central1"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      # Configure auth with Service Account with permissions to build and deploy on Google Cloud
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_IAM_SA_CREDENTIALS }}

      # BEGIN - Docker auth and build
      - name: "Docker Auth"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ env.AR_REGION }}-docker.pkg.dev"
          username: _json_key
          password: ${{ secrets.GCP_IAM_SA_CREDENTIALS }}

      - name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.AR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo $DOCKER_TAG
          docker build --tag "${DOCKER_TAG}" --build-arg IS_PROD_ARG=1 --build-arg GITHUB_SHA_ARG="${{ github.sha }}" .
          docker push "${DOCKER_TAG}"
        # END - Docker auth and build

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.AR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
